//! Integration test: run a real, fetched isaacsim wheel METADATA through
//! retread's relax pipeline and assert that the resulting conda dependencies
//! no longer carry the patch-exact pins that make a workspace with ros2
//! refuse to solve.
//!
//! The METADATA fixtures are regenerated by
//! `tests/fixtures/fetch_metadata.py`. Re-run that script whenever a wheel
//! is re-released upstream; the diff in the committed `.METADATA.txt` and
//! `.json` files is the audit trail for what changed.
//!
//! The conflict story lifted from
//! https://github.com/prefix-dev/pixi/issues/5230: gigastrap's `gsi-ros2`
//! environment combines `feature.ros2`'s conda `ros-humble-*` packages with
//! the PyPI `isaacsim` metapackage. Isaac Sim's wheels pin every transitive
//! to exact patch versions (`numpy==1.26.0`, `pillow==11.3.0`, ...), which
//! collides with whatever conda has already pinned for the ros2 side. The
//! workaround documented in the issue is a 50-line block of
//! `[pypi-options.dependency-overrides]`. With retread set to
//! `relax = "minor"`, those overrides become unnecessary because the
//! generated conda package's run-deps are widened to compatible ranges.

use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

use pixi_build_retread::config::{RelaxPolicy, RetreadConfig};
use pixi_build_retread::recipe::{BundleSource, build_bundle_recipe, to_yaml};
use pixi_build_retread::wheel::parse_metadata;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn load_fixture(slug: &str) -> (String, String, String, bool) {
    let dir = fixtures_dir();
    let metadata = fs::read_to_string(dir.join(format!("{slug}.METADATA.txt")))
        .unwrap_or_else(|e| panic!("missing fixture {slug}.METADATA.txt — run tests/fixtures/fetch_metadata.py to regenerate ({e})"));
    let manifest: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(dir.join(format!("{slug}.json"))).unwrap())
            .unwrap();
    let filename = manifest["filename"].as_str().unwrap().to_string();
    let sha256 = manifest["sha256"].as_str().unwrap().to_string();
    let is_pure_python = filename.contains("-none-any.whl");
    (metadata, filename, sha256, is_pure_python)
}

fn baseline_config() -> RetreadConfig {
    // Intentionally stripped: no overrides, no name-map. The whole point is
    // proving relax='minor' alone is enough to let ros2 + isaacsim coexist.
    // Compare to gigastrap's `[feature.isaaclab.pypi-options.dependency-overrides]`
    // block in /home/garylvov/projects/gigastrap/pixi.toml — that's what
    // should NOT be needed once retread is in the loop.
    RetreadConfig {
        retread_wheels: BTreeMap::new(),
        relax: RelaxPolicy::Minor,
        overrides: BTreeMap::new(),
        name_map: BTreeMap::new(),
        build_number: 0,
        drop_deps: Vec::new(),
        auto_bundle: false,
        conda_deps: Vec::new(),
        default_bundle: None,
        compression_level: None,
        git_sources: std::collections::BTreeMap::new(),
        python: None,
    }
}

/// Pluck the run-deps line for a given package name out of the rendered YAML.
fn find_run_dep<'a>(yaml: &'a str, package: &str) -> Option<&'a str> {
    let mut in_run = false;
    for line in yaml.lines() {
        if line.trim_start().starts_with("run:") {
            in_run = true;
            continue;
        }
        if in_run {
            if !line.starts_with(char::is_whitespace) && !line.is_empty() {
                // Left the `run:` block.
                in_run = false;
                continue;
            }
            let stripped = line.trim_start().trim_start_matches("- ").trim();
            if stripped.starts_with(package)
                && stripped[package.len()..]
                    .chars()
                    .next()
                    .is_none_or(|c| c == ' ' || c == '=' || c == '>' || c == '<')
            {
                return Some(stripped);
            }
        }
    }
    None
}

#[test]
fn isaacsim_kernel_pins_widen_under_minor_relax() {
    let (raw, filename, sha256, pure) = load_fixture("isaacsim_kernel");
    let metadata = parse_metadata(&raw, filename.clone(), pure, sha256).unwrap();
    let url: url::Url = format!("https://pypi.nvidia.com/isaacsim-kernel/{filename}")
        .parse()
        .unwrap();

    let recipe = build_bundle_recipe(
        "isaacsim-test",
        &[BundleSource {
            pypi_name: &metadata.name,
            url: &url,
            metadata: &metadata,
        }],
        &baseline_config(),
        "3.11",
        None,
    )
    .unwrap();
    let yaml = to_yaml(&recipe).unwrap();

    // These are the deps that the manual gigastrap workaround pins to keep
    // ros2 + isaacsim happy. With retread, each should appear in the rendered
    // recipe as a *range*, not an exact pin.
    let numpy = find_run_dep(&yaml, "numpy").expect("numpy must appear in run deps");
    let pillow = find_run_dep(&yaml, "pillow").expect("pillow must appear in run deps");
    let requests = find_run_dep(&yaml, "requests").expect("requests must appear in run deps");

    // Real isaacsim-kernel 5.1.0 pins: numpy==1.26.0, Pillow==11.3.0,
    // requests==2.32.3. Under minor relax we expect "name >=X.Y,<X+1".
    assert!(
        numpy.starts_with("numpy >=1.26,<"),
        "numpy should be widened to a minor range, got: {numpy}"
    );
    assert!(
        pillow.starts_with("pillow >=11.3,<") || pillow.starts_with("pillow >=11,<"),
        "pillow should be widened, got: {pillow}"
    );
    assert!(
        requests.starts_with("requests >=2.32,<3"),
        "requests should be widened, got: {requests}"
    );

    // No exact pin should leak through (sanity: == followed by a digit).
    for line in yaml.lines() {
        let t = line.trim_start();
        if let Some(spec) = t.strip_prefix("- ") {
            assert!(
                !spec.contains(" =="),
                "found exact pin under minor relax: {spec}\nfull recipe:\n{yaml}"
            );
        }
    }
}

#[test]
fn isaacsim_core_compat_with_ros2_workspace_pins() {
    // gigastrap's global [dependencies] sets scipy==1.16.3 (conda). isaacsim-core
    // wants scipy==1.15.3. Without retread that's an unresolvable conflict.
    // Under minor relax, isaacsim-core's spec widens to ">=1.15,<2" which is
    // satisfied by conda's 1.16.3.
    let (raw, filename, sha256, pure) = load_fixture("isaacsim_core");
    let metadata = parse_metadata(&raw, filename.clone(), pure, sha256).unwrap();
    let url: url::Url = format!("https://pypi.nvidia.com/isaacsim-core/{filename}")
        .parse()
        .unwrap();
    let recipe = build_bundle_recipe(
        "isaacsim-test",
        &[BundleSource {
            pypi_name: &metadata.name,
            url: &url,
            metadata: &metadata,
        }],
        &baseline_config(),
        "3.11",
        None,
    )
    .unwrap();
    let yaml = to_yaml(&recipe).unwrap();

    let scipy = find_run_dep(&yaml, "scipy").expect("scipy must appear");
    assert!(
        scipy.starts_with("scipy >=1.15,<"),
        "scipy should widen to a minor range that covers 1.16.x, got: {scipy}",
    );

    // packaging is also a ros2-side conflict source (isaacsim-core pins
    // packaging==23.0 hard; most ros-humble-* require >=23 or >=24). Under
    // minor relax the constraint becomes >=23,<24 — still problematic for
    // ros2-humble in some configurations.
    let packaging = find_run_dep(&yaml, "packaging").expect("packaging must appear");
    assert!(
        packaging.starts_with("packaging >=23"),
        "packaging should widen from exact 23.0, got: {packaging}"
    );
}

#[test]
fn name_map_remaps_opencv_to_conda() {
    let (raw, filename, sha256, pure) = load_fixture("isaacsim_core");
    let metadata = parse_metadata(&raw, filename.clone(), pure, sha256).unwrap();
    let url: url::Url = format!("https://pypi.nvidia.com/isaacsim-core/{filename}")
        .parse()
        .unwrap();

    // gigastrap-style: PyPI opencv-python-headless -> conda py-opencv.
    let mut cfg = baseline_config();
    cfg.name_map
        .insert("opencv-python-headless".into(), "py-opencv".into());
    let recipe = build_bundle_recipe(
        "isaacsim-test",
        &[BundleSource {
            pypi_name: &metadata.name,
            url: &url,
            metadata: &metadata,
        }],
        &cfg,
        "3.11",
        None,
    )
    .unwrap();
    let yaml = to_yaml(&recipe).unwrap();

    assert!(
        yaml.contains("py-opencv "),
        "name-map should rewrite opencv-python-headless to py-opencv. yaml:\n{yaml}"
    );
    assert!(
        !yaml.contains("opencv-python-headless"),
        "opencv-python-headless should not appear after remap. yaml:\n{yaml}"
    );
}

#[test]
fn aggressive_major_relax_drops_upper_bounds() {
    // Demonstrate that the policy knob actually works end-to-end.
    let (raw, filename, sha256, pure) = load_fixture("isaacsim_kernel");
    let metadata = parse_metadata(&raw, filename.clone(), pure, sha256).unwrap();
    let url: url::Url = format!("https://pypi.nvidia.com/isaacsim-kernel/{filename}")
        .parse()
        .unwrap();

    let mut cfg = baseline_config();
    cfg.relax = RelaxPolicy::Major;
    let recipe = build_bundle_recipe(
        "isaacsim-test",
        &[BundleSource {
            pypi_name: &metadata.name,
            url: &url,
            metadata: &metadata,
        }],
        &cfg,
        "3.11",
        None,
    )
    .unwrap();
    let yaml = to_yaml(&recipe).unwrap();

    let numpy = find_run_dep(&yaml, "numpy").expect("numpy must appear");
    assert_eq!(numpy, "numpy >=1", "major relax drops upper bound: {numpy}");
}
