#!/usr/bin/env python3
"""Generate per-Python-minor stdlib name tables for src/import_scan.rs.

Rust cannot ask the interpreter: `sys.stdlib_module_names` is a runtime value.
So the table is VENDORED and this script regenerates it. Run it with each
target interpreter; it writes stdlib_<major>_<minor>.txt next to itself.

TWO SOURCES, because `sys.stdlib_module_names` was added in 3.10:
  * 3.10+  -> sys.stdlib_module_names (authoritative)
  * <=3.9  -> sys.builtin_module_names + a scan of the stdlib directory
              (approximate; marked as such in the header so nobody mistakes
              it for the authoritative set)

Usage:  <python> gen_stdlib_tables.py [outdir]
"""
import os, sys

def names():
    if hasattr(sys, "stdlib_module_names"):
        return set(sys.stdlib_module_names), "sys.stdlib_module_names"
    out = set(sys.builtin_module_names)
    libdir = os.path.dirname(os.__file__)
    for e in os.listdir(libdir):
        p = os.path.join(libdir, e)
        if e.endswith(".py") and e != "__init__.py":
            out.add(e[:-3])
        elif os.path.isdir(p) and os.path.exists(os.path.join(p, "__init__.py")):
            if e not in ("site-packages", "dist-packages", "lib-dynload"):
                out.add(e)
    for e in os.listdir(os.path.join(libdir, "lib-dynload")) if os.path.isdir(
            os.path.join(libdir, "lib-dynload")) else []:
        out.add(e.split(".")[0])
    return out, "builtin_module_names + stdlib dir scan (APPROXIMATE)"

def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.abspath(__file__))
    n, src = names()
    n = {x for x in n if x and not x.startswith("_")} | {x for x in n if x.startswith("_")}
    v = f"{sys.version_info.major}.{sys.version_info.minor}"
    path = os.path.join(outdir, f"stdlib_{sys.version_info.major}_{sys.version_info.minor}.txt")
    with open(path, "w") as fh:
        fh.write(f"# GENERATED by gen_stdlib_tables.py -- DO NOT HAND-EDIT\n")
        fh.write(f"# python {sys.version.split()[0]}  minor {v}  source: {src}\n")
        fh.write(f"# count {len(n)}\n")
        for name in sorted(n):
            fh.write(name + "\n")
    print(f"{v}: {len(n)} names -> {path}  ({src})")

main()
