//! Static PEP 621 metadata for the workspace's local PyPI **path sources**,
//! supplied entirely from the PACK LAYER — a hand-editable record file beside
//! the pack's own manifest, and a GENERATED shim directory inside the pack
//! directory that the workspace manifest points its `path =` entry at.
//!
//! # The defect this closes
//!
//! pixi resolves `[pypi-dependencies]` entries of the form
//! `name = { path = "…", editable = true }` with its OWN uv (the frontend
//! resolver in `pixi_core::lock_file::resolve::pypi`), not with retread's
//! child uv. uv reads a path source's metadata statically only when the tree
//! carries a `[project]` table whose needed fields (`name`, `version`,
//! `requires-python`, `dependencies`) are present and are NOT listed in
//! `dynamic`. When they are not, uv logs
//!
//! ```text
//! No static `pyproject.toml` available for: pace-sim2real @ file:///… (FieldNotFound("project"))
//! Preparing metadata for: pace-sim2real @ file:///…
//! ```
//!
//! and runs a full PEP 517 `prepare_metadata_for_build_wheel`: pixi
//! instantiates a whole conda build environment for that one tree. On the
//! campaign's canonical 27-environment workspace that cost 1 714.7 s of a
//! 1 758 s lock for a 27-file, 40 KB source tree whose own build work is
//! 6.2 s.
//!
//! # Why the SHIM and not an overlay on the tree (the p6m → p6m-b change)
//!
//! p6m wrote the `[project]` block into the WORKSPACE copy of the real tree.
//! Correct and fast, but in production the workspace IS `imprint-data`, so
//! the overlay landed in `third_party/ProtoMotions` (an untracked new file)
//! and in `third_party/pace-sim2real/…/pyproject.toml` (an appended block) —
//! a dirty `git status` in trees we do not own, forever.
//!
//! p6m-b moves BOTH halves into the pack directory, where retread already
//! owns everything:
//!
//! * **the record** — `<pack>/path-sources/<project>.toml`, one file per
//!   project, hand-editable, the SOURCE OF TRUTH, and the only thing a human
//!   ever edits;
//! * **the shim** — `<pack>/sources/<project>/pyproject.toml`, GENERATED from
//!   that record on every `initialize`, never hand-edited, a pure function of
//!   the record plus the relative path to the real tree.
//!
//! The workspace manifest then reads
//!
//! ```toml
//! pace_sim2real = { path = "pypi-packs/isaaclab-2.3x-pack/sources/pace-sim2real", editable = true }
//! ```
//!
//! and **not one byte is written outside the pack directory**. The real tree
//! is reached from the shim by `[tool.setuptools] package-dir` /
//! `packages.find.where`, both relative, so the editable install's finder
//! resolves into the real tree and an edit there is live with no reinstall.
//!
//! It also removes p6m's one known limit. p6m's overlay was a side effect of
//! a backend invocation, so an environment declaring no retread pack
//! (`pm-mujoco`) could in principle resolve before any backend initialized.
//! The shim is tracked pack content: it is on disk before pixi starts, and
//! `initialize` only REFRESHES it.
//!
//! # Updatability — drift is loud, refresh is one command
//!
//! The record is a claim about a tree that upstream can bump under us. Every
//! `initialize` re-reads the tree's own statements of those facts
//! (`*.egg-info/PKG-INFO`, `config/extension.toml`, `setup.py`) and REFUSES,
//! naming the record file, the field, both values and the tree file that
//! disagrees. Nothing is silently overwritten in either direction:
//! `pixi-build-retread path-source-refresh --pack <dir> --workspace <dir>
//! [--write]` prints the diff and, with `--write`, rewrites the record FROM
//! the tree so the operator reviews one small diff.
//!
//! # The three things this module refuses to do
//!
//! * **Write outside the pack directory.** Every write goes through
//!   [`write_under_pack`], which fails if the target is not under the pack
//!   root. Pointing the writer at `third_party/…` fails the guard.
//! * **Write through a hardlink.** A staged workspace is `cp -al`'d out of a
//!   shared mirror. The shim file is written to a sibling temp and `rename`d
//!   over the name, which replaces the *directory entry*; every other link
//!   keeps the old inode. The written file is asserted to have one link.
//! * **Invent a path source.** If the consuming `pixi.toml` does not declare
//!   the shim's own path, the record is stale and nothing is written.

use std::collections::BTreeMap;
use std::path::{Component, Path, PathBuf};

use anyhow::{Context, Result, bail};
use serde::{Deserialize, Serialize};

use crate::config::RetreadConfig;

/// First line of the generated shim. Also the idempotence key and the
/// "do not hand-edit this" sign: the record file is the editable half.
pub const GENERATED_MARKER: &str =
    "# --- generated by pixi-build-retread (retread-path-source-metadata). Do not edit; edit the record beside the pack manifest. ---";

/// Last line of the generated shim.
pub const GENERATED_END: &str = "# --- end pixi-build-retread generated shim ---";

/// The PEP 621 fields uv needs statically.
pub const REQUIRED_STATIC_FIELDS: [&str; 4] =
    ["name", "version", "requires-python", "dependencies"];

/// Default directory, relative to the pack directory, holding the records.
/// One `<project>.toml` per project — "keyed by project", beside the pack's
/// own `retread-*.json` outputs.
pub const RECORDS_DIR_DEFAULT: &str = "path-sources";

/// Directory, relative to the pack directory, holding the generated shims.
/// `<pack>/sources/<project>/` is what the workspace manifest points at.
pub const SHIMS_DIR: &str = "sources";

/// One declared path source, read from `<pack>/path-sources/<project>.toml`.
///
/// **This file is the source of truth and the only hand-edited artifact.**
/// Everything in it is a FACT ABOUT THE REAL TREE, not a preference: it is
/// what a PEP 517 metadata build of that tree produces today, and every field
/// the tree also states for itself is cross-checked on every run.
#[derive(Debug, Clone, Default, Deserialize, Serialize, PartialEq, Eq)]
#[serde(deny_unknown_fields, rename_all = "kebab-case")]
pub struct PathSourceEntry {
    /// Path to the REAL source tree, relative to the workspace root — the
    /// string the workspace manifest used before the shim replaced it.
    pub path: String,

    /// The project's version, as the tree's own build backend produces it.
    pub version: String,

    /// `requires-python`, e.g. `">=3.10"`. Omitted means the source declares
    /// none.
    #[serde(default)]
    pub requires_python: Option<String>,

    /// PEP 508 runtime dependencies, in the order the source declares them.
    #[serde(default)]
    pub dependencies: Vec<String>,

    /// Glob(s) selecting the importable packages inside the real tree.
    /// Defaults to `["<project-underscored>*"]`, which is what both live
    /// trees need (`pace_sim2real*`, `protomotions*`). Present because a
    /// tree with an unusual layout is a fact about the tree, not a
    /// preference.
    #[serde(default)]
    pub packages_include: Vec<String>,
}

impl PathSourceEntry {
    /// The `packages.find.include` globs to render, defaulted from the
    /// project name.
    pub fn include_globs(&self, project: &str) -> Vec<String> {
        if !self.packages_include.is_empty() {
            return self.packages_include.clone();
        }
        vec![format!("{}*", project.replace(['-', '.'], "_"))]
    }
}

/// A record file on disk, with the project it is keyed by.
#[derive(Debug, Clone)]
pub struct PathSourceRecord {
    /// The file stem — the project key. `pace-sim2real`, `protomotions`.
    pub project: String,
    /// The record file itself. Every refusal names it: it is what to edit.
    pub file: PathBuf,
    pub entry: PathSourceEntry,
}

/// What happened to one declared source.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PathSourceOutcome {
    /// The shim was written or regenerated.
    Written { project: String, shim: PathBuf },
    /// The shim on disk already had identical bytes. No write.
    Unchanged { project: String, shim: PathBuf },
}

impl PathSourceOutcome {
    pub fn project(&self) -> &str {
        match self {
            Self::Written { project, .. } | Self::Unchanged { project, .. } => project,
        }
    }
    pub fn shim(&self) -> &Path {
        match self {
            Self::Written { shim, .. } | Self::Unchanged { shim, .. } => shim,
        }
    }
    pub fn verb(&self) -> &'static str {
        match self {
            Self::Written { .. } => "written",
            Self::Unchanged { .. } => "unchanged",
        }
    }
}

/// PEP 503 name normalization, so `pace_sim2real`, `pace-sim2real` and
/// `PACE.Sim2Real` compare equal.
pub fn normalize_dist_name(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut last_dash = false;
    for ch in name.chars() {
        if ch == '-' || ch == '_' || ch == '.' {
            if !last_dash {
                out.push('-');
                last_dash = true;
            }
        } else {
            out.push(ch.to_ascii_lowercase());
            last_dash = false;
        }
    }
    out
}

// ---------------------------------------------------------------------------
// facts the TREE states about itself — the drift detector's right-hand side
// ---------------------------------------------------------------------------

/// One fact the real tree states, and the file that states it. Both are in
/// every refusal message: "your record says X, `<file>` says Y".
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TreeFact {
    pub value: String,
    pub source: PathBuf,
}

/// Everything the real tree says about itself, from every place it says it.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct TreeFacts {
    pub name: Option<TreeFact>,
    pub version: Option<TreeFact>,
    pub requires_python: Option<TreeFact>,
    /// `None` = the tree states nothing about its dependencies anywhere, so
    /// there is nothing to check. `Some(vec![])` = it states that it has
    /// none (protomotions' PKG-INFO with no `Requires-Dist` lines).
    pub dependencies: Option<(Vec<String>, PathBuf)>,
}

/// Read the tree's own statements of the four fields.
///
/// Three readers, in decreasing authority:
///  1. `*.egg-info/PKG-INFO` — written by the tree's own build backend, so it
///     is exactly what a metadata build would produce. All four fields.
///  2. `config/extension.toml` `[package] version` — what `pace-sim2real`'s
///     `setup.py` `toml.load`s at build time.
///  3. `setup.py` literal `version=` / `python_requires=` — what
///     `ProtoMotions` states in source.
///
/// A later reader never overrides an earlier one; it only fills a gap. A
/// missing tree is not an error here (the caller has already refused).
pub fn tree_facts(dir: &Path) -> Result<TreeFacts> {
    let mut facts = TreeFacts::default();

    if let Some(pkg_info) = find_pkg_info(dir)? {
        let text = std::fs::read_to_string(&pkg_info)
            .with_context(|| format!("reading {}", pkg_info.display()))?;
        let mut requires_dist = Vec::new();
        let mut saw_headers = false;
        for line in text.lines() {
            if line.is_empty() {
                break; // headers end at the first blank line
            }
            let Some((key, value)) = line.split_once(':') else {
                continue;
            };
            saw_headers = true;
            let value = value.trim().to_string();
            let fact = TreeFact {
                value: value.clone(),
                source: pkg_info.clone(),
            };
            match key.to_ascii_lowercase().as_str() {
                "name" => {
                    facts.name.get_or_insert(fact);
                }
                "version" => {
                    facts.version.get_or_insert(fact);
                }
                "requires-python" => {
                    facts.requires_python.get_or_insert(fact);
                }
                "requires-dist" => requires_dist.push(value),
                _ => {}
            }
        }
        if saw_headers {
            facts.dependencies = Some((requires_dist, pkg_info));
        }
    }

    // pace-sim2real: setup.py reads config/extension.toml at build time.
    let ext = dir.join("config").join("extension.toml");
    if facts.version.is_none() && ext.is_file() {
        let text = std::fs::read_to_string(&ext)
            .with_context(|| format!("reading {}", ext.display()))?;
        if let Ok(value) = toml::from_str::<toml::Value>(&text)
            && let Some(v) = value
                .get("package")
                .and_then(|p| p.get("version"))
                .and_then(|v| v.as_str())
        {
            facts.version = Some(TreeFact {
                value: v.to_string(),
                source: ext,
            });
        }
    }

    // ProtoMotions: literal keywords in setup.py.
    let setup_py = dir.join("setup.py");
    if setup_py.is_file() {
        let text = std::fs::read_to_string(&setup_py)
            .with_context(|| format!("reading {}", setup_py.display()))?;
        if facts.version.is_none()
            && let Some(v) = scan_setup_kwarg(&text, "version")
        {
            facts.version = Some(TreeFact {
                value: v,
                source: setup_py.clone(),
            });
        }
        if facts.requires_python.is_none()
            && let Some(v) = scan_setup_kwarg(&text, "python_requires")
        {
            facts.requires_python = Some(TreeFact {
                value: v,
                source: setup_py.clone(),
            });
        }
        if facts.name.is_none()
            && let Some(v) = scan_setup_kwarg(&text, "name")
        {
            facts.name = Some(TreeFact {
                value: v,
                source: setup_py,
            });
        }
    }

    Ok(facts)
}

/// `version="3.1"` / `python_requires='>=3.8'` — a literal keyword argument
/// with a quoted string value. Deliberately only literals: a computed value
/// is not a fact this can read, and guessing one would be worse than the
/// PKG-INFO it falls back to.
fn scan_setup_kwarg(text: &str, kwarg: &str) -> Option<String> {
    for line in text.lines() {
        let trimmed = line.trim_start();
        let Some(rest) = trimmed.strip_prefix(kwarg) else {
            continue;
        };
        let rest = rest.trim_start();
        let Some(rest) = rest.strip_prefix('=') else {
            continue;
        };
        let rest = rest.trim_start();
        let Some(quote) = rest.chars().next() else {
            continue;
        };
        if quote != '"' && quote != '\'' {
            continue;
        }
        let body = &rest[1..];
        if let Some(end) = body.find(quote) {
            return Some(body[..end].to_string());
        }
    }
    None
}

/// Compare the record against the tree and refuse on any disagreement,
/// naming the record file (what to edit), the field, and both values with
/// the tree file that states the other one.
pub fn check_drift(record: &PathSourceRecord, facts: &TreeFacts) -> Result<()> {
    let file = record.file.display();
    if let Some(fact) = &facts.name
        && normalize_dist_name(&fact.value) != normalize_dist_name(&record.project)
    {
        bail!(
            "path-source record drift: {file} is keyed `{}`, but {} says the \
             project is named `{}`. Edit {file} (or rename it), or run \
             `pixi-build-retread path-source-refresh --write`.",
            record.project,
            fact.source.display(),
            fact.value,
        );
    }
    if let Some(fact) = &facts.version
        && fact.value != record.entry.version
    {
        bail!(
            "path-source record drift: {file} declares `version = \"{}\"`, but \
             {} says `{}`. The record is stale — the lock would claim a version \
             the installed tree does not have. Edit the `version` field of \
             {file}, or run `pixi-build-retread path-source-refresh --write` and \
             review the diff.",
            record.entry.version,
            fact.source.display(),
            fact.value,
        );
    }
    if let Some(fact) = &facts.requires_python
        && Some(fact.value.as_str()) != record.entry.requires_python.as_deref()
    {
        bail!(
            "path-source record drift: {file} declares `requires-python = {:?}`, \
             but {} says `{}`. Edit the `requires-python` field of {file}, or \
             run `pixi-build-retread path-source-refresh --write`.",
            record.entry.requires_python,
            fact.source.display(),
            fact.value,
        );
    }
    if let Some((deps, source)) = &facts.dependencies
        && deps != &record.entry.dependencies
    {
        bail!(
            "path-source record drift: {file} declares `dependencies = {:?}`, but \
             {} lists {:?}. A dependency the record omits is a dependency the \
             resolver will never see. Edit the `dependencies` field of {file}, or \
             run `pixi-build-retread path-source-refresh --write`.",
            record.entry.dependencies,
            source.display(),
            deps,
        );
    }
    Ok(())
}

/// Build the record a tree's own facts imply — the `--write` half of
/// `path-source-refresh`. Everything the tree does not state is carried over
/// from the current record, so a refresh never invents and never drops.
pub fn record_from_tree(
    project: &str,
    current: &PathSourceEntry,
    facts: &TreeFacts,
) -> Result<PathSourceEntry> {
    let Some(version) = facts.version.as_ref().map(|f| f.value.clone()) else {
        bail!(
            "cannot refresh `{project}` from the tree: nothing in it states a \
             version (no *.egg-info/PKG-INFO, no config/extension.toml \
             [package] version, no literal `version=` in setup.py). Edit the \
             record by hand."
        );
    };
    Ok(PathSourceEntry {
        path: current.path.clone(),
        version,
        requires_python: facts
            .requires_python
            .as_ref()
            .map(|f| f.value.clone())
            .or_else(|| current.requires_python.clone()),
        dependencies: facts
            .dependencies
            .as_ref()
            .map(|(d, _)| d.clone())
            .unwrap_or_else(|| current.dependencies.clone()),
        packages_include: current.packages_include.clone(),
    })
}

// ---------------------------------------------------------------------------
// records on disk
// ---------------------------------------------------------------------------

/// Load every `<project>.toml` under `<pack>/<records_dir>/`, sorted by
/// project so a run's log order is stable.
pub fn load_records(pack_dir: &Path, records_dir: &str) -> Result<Vec<PathSourceRecord>> {
    let dir = pack_dir.join(records_dir);
    if !dir.is_dir() {
        return Ok(Vec::new());
    }
    let mut out = Vec::new();
    for entry in
        std::fs::read_dir(&dir).with_context(|| format!("reading {}", dir.display()))?
    {
        let entry = entry?;
        let file = entry.path();
        if file.extension().and_then(|e| e.to_str()) != Some("toml") {
            continue;
        }
        let project = file
            .file_stem()
            .and_then(|s| s.to_str())
            .ok_or_else(|| anyhow::anyhow!("{} has no usable file stem", file.display()))?
            .to_string();
        let text = std::fs::read_to_string(&file)
            .with_context(|| format!("reading {}", file.display()))?;
        let parsed: PathSourceEntry = toml::from_str(&text)
            .with_context(|| format!("parsing {} as a path-source record", file.display()))?;
        out.push(PathSourceRecord {
            project,
            file,
            entry: parsed,
        });
    }
    out.sort_by(|a, b| a.project.cmp(&b.project));
    Ok(out)
}

/// Serialize a record back to its file's text. Round-trips
/// [`PathSourceEntry`] exactly, so `refresh --write` produces a diff of only
/// the fields that moved.
pub fn render_record(project: &str, entry: &PathSourceEntry) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# Path-source metadata record for `{project}`.\n\
         #\n\
         # THIS FILE IS THE SOURCE OF TRUTH and the only half a human edits.\n\
         # `../{SHIMS_DIR}/{project}/pyproject.toml` is GENERATED from it on every\n\
         # backend initialize and must not be edited.\n\
         #\n\
         # Every field is a FACT about the tree at `path`, cross-checked against\n\
         # the tree's own *.egg-info/PKG-INFO, config/extension.toml and setup.py\n\
         # on every run. A disagreement is a hard refusal naming this file.\n\
         # To adopt the tree's current facts:\n\
         #   pixi-build-retread path-source-refresh --pack <this pack dir> \\\n\
         #       --workspace <workspace root> --project {project} --write\n\n"
    ));
    out.push_str(&format!("path = {}\n", toml_string(&entry.path)));
    out.push_str(&format!("version = {}\n", toml_string(&entry.version)));
    if let Some(rp) = entry.requires_python.as_deref() {
        out.push_str(&format!("requires-python = {}\n", toml_string(rp)));
    }
    out.push_str(&format!("dependencies = {}\n", toml_array(&entry.dependencies)));
    if !entry.packages_include.is_empty() {
        out.push_str(&format!(
            "packages-include = {}\n",
            toml_array(&entry.packages_include)
        ));
    }
    out
}

// ---------------------------------------------------------------------------
// the production path
// ---------------------------------------------------------------------------

/// THE production entry point, and the one the guards call.
///
/// Both the gate and the write live behind this single name on purpose: a
/// guard that called a lower-level helper would stay green when the call in
/// `Handler::initialize` is deleted, so the gate check is INSIDE here and the
/// wiring test drives `initialize` itself.
pub fn materialize_declared_path_sources(
    config: &RetreadConfig,
    workspace_dir: Option<&Path>,
    pack_manifest_path: Option<&Path>,
) -> Result<Vec<PathSourceOutcome>> {
    let records_dir = config
        .path_source_records
        .as_deref()
        .unwrap_or(RECORDS_DIR_DEFAULT);

    let pack_dir = pack_manifest_path.and_then(|p| p.parent()).map(Path::to_path_buf);

    if !config.path_source_metadata.unwrap_or(false) {
        if let Some(dir) = pack_dir.as_deref()
            && let Ok(found) = load_records(dir, records_dir)
            && !found.is_empty()
        {
            tracing::warn!(
                "{}/{} holds {} path-source record(s) but \
                 retread-path-source-metadata is not true: no shim will be \
                 refreshed and the frontend resolver will run a PEP 517 \
                 metadata build for each of them.",
                dir.display(),
                records_dir,
                found.len()
            );
        }
        return Ok(Vec::new());
    }

    let Some(pack_dir) = pack_dir else {
        bail!(
            "retread-path-source-metadata = true but this backend was not given \
             a manifest path, so the pack directory holding the records and the \
             generated shims cannot be located."
        );
    };
    let Some(workspace_root) = workspace_dir.filter(|dir| dir.join("pixi.toml").is_file()) else {
        bail!(
            "retread-path-source-metadata = true but this backend was not given \
             a workspace directory containing a pixi.toml. The real trees are \
             located relative to the workspace root, and the shim's own path \
             must be the one the workspace manifest declares."
        );
    };
    let outcomes = generate_shims(&pack_dir, workspace_root, records_dir, None)?;
    if outcomes.is_empty() {
        bail!(
            "retread-path-source-metadata = true but {}/{} holds no \
             <project>.toml record. A gate with no producer is a defect: either \
             write the records or drop the key.",
            pack_dir.display(),
            records_dir
        );
    }
    Ok(outcomes)
}

/// Generate (or refresh) every shim this pack's records describe.
///
/// This is the SINGLE writer, shared by `Handler::initialize` and by the
/// `path-source-refresh --shims` CLI verb — the command a developer runs once
/// to materialize the shim they then COMMIT as pack content. The two callers
/// must not drift: a shim a developer committed and a shim `initialize`
/// regenerates are the same bytes, which is what makes `initialize` a no-op on
/// a clean checkout.
pub fn generate_shims(
    pack_dir: &Path,
    workspace_root: &Path,
    records_dir: &str,
    only: Option<&str>,
) -> Result<Vec<PathSourceOutcome>> {
    // A pack is identified by its own manifest. Without this, any directory
    // handed to `--pack` becomes a write root, and the one thing this
    // capability must never do is write into a directory that is not a pack.
    if !pack_dir.join("pixi.toml").is_file() {
        bail!(
            "{} is not a pack directory: it holds no pixi.toml. retread \
             generates path-source shims into a PACK and nowhere else.",
            pack_dir.display()
        );
    }
    let records = load_records(pack_dir, records_dir)?;
    let manifest_text = std::fs::read_to_string(workspace_root.join("pixi.toml"))
        .with_context(|| format!("reading {}", workspace_root.join("pixi.toml").display()))?;
    let mut outcomes = Vec::with_capacity(records.len());
    for record in &records {
        if let Some(only) = only
            && only != record.project
        {
            continue;
        }
        let outcome = materialize_one(pack_dir, workspace_root, &manifest_text, record)
            .with_context(|| format!("path-source record {}", record.file.display()))?;
        tracing::info!(
            "retread-path-source-metadata: {} {} ({})",
            outcome.verb(),
            outcome.shim().display(),
            outcome.project(),
        );
        outcomes.push(outcome);
    }
    Ok(outcomes)
}

fn materialize_one(
    pack_dir: &Path,
    workspace_root: &Path,
    manifest_text: &str,
    record: &PathSourceRecord,
) -> Result<PathSourceOutcome> {
    let entry = &record.entry;

    // ---- the record itself -------------------------------------------------
    if entry.path.trim().is_empty() {
        bail!("`path` is empty");
    }
    if entry.version.trim().is_empty() {
        bail!("`version` is empty: uv needs a static version or it builds anyway");
    }

    // ---- where the REAL tree is --------------------------------------------
    let rel = Path::new(&entry.path);
    if rel.is_absolute() {
        bail!("`path` must be relative to the workspace root, got {}", entry.path);
    }
    if rel
        .components()
        .any(|c| matches!(c, Component::ParentDir | Component::Prefix(_) | Component::RootDir))
    {
        bail!("`path` may not escape the workspace root, got {}", entry.path);
    }
    let real_dir = workspace_root.join(rel);
    if !real_dir.is_dir() {
        bail!("{} is not a directory", real_dir.display());
    }
    let canonical_root = workspace_root
        .canonicalize()
        .with_context(|| format!("canonicalizing {}", workspace_root.display()))?;
    let canonical_real = real_dir
        .canonicalize()
        .with_context(|| format!("canonicalizing {}", real_dir.display()))?;
    if !canonical_real.starts_with(&canonical_root) {
        bail!(
            "{} resolves to {}, which is outside the workspace root {}",
            entry.path,
            canonical_real.display(),
            canonical_root.display()
        );
    }

    // ---- the facts must still be the tree's facts --------------------------
    let facts = tree_facts(&real_dir)?;
    check_drift(record, &facts)?;

    // ---- where the SHIM goes, and the reader/writer tie --------------------
    let shim_dir = pack_dir.join(SHIMS_DIR).join(&record.project);
    let shim_rel_to_ws = pathdiff_from_root(&canonical_root, &shim_dir)?;
    if !manifest_text.contains(&format!("\"{shim_rel_to_ws}\""))
        && !manifest_text.contains(&format!("'{shim_rel_to_ws}'"))
    {
        bail!(
            "the workspace manifest declares no path source `{shim_rel_to_ws}`; \
             refusing to generate a shim nothing resolves. Point the \
             `[pypi-dependencies]` entry for `{}` at it:\n    {} = {{ path = \
             \"{shim_rel_to_ws}\", editable = true }}",
            record.project,
            record.project.replace('-', "_"),
        );
    }

    // ---- relative path from the SHIM back to the real tree -----------------
    let rel_to_real = relative_from_shim(&shim_rel_to_ws, &entry.path);

    // ---- compose and write -------------------------------------------------
    let composed = render_shim_pyproject(&record.project, entry, &rel_to_real);
    let shim_file = shim_dir.join("pyproject.toml");
    let existing = match std::fs::read_to_string(&shim_file) {
        Ok(text) => Some(text),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => None,
        Err(err) => return Err(err).with_context(|| format!("reading {}", shim_file.display())),
    };
    if existing.as_deref() == Some(composed.as_str()) {
        verify_shim(&shim_file, &record.project, entry)?;
        return Ok(PathSourceOutcome::Unchanged {
            project: record.project.clone(),
            shim: shim_dir,
        });
    }
    write_under_pack(pack_dir, &shim_dir, None)?;
    std::fs::create_dir_all(&shim_dir)
        .with_context(|| format!("creating {}", shim_dir.display()))?;
    write_under_pack(pack_dir, &shim_file, Some(composed.as_str()))?;
    verify_shim(&shim_file, &record.project, entry)?;
    Ok(PathSourceOutcome::Written {
        project: record.project.clone(),
        shim: shim_dir,
    })
}

/// The generated shim `pyproject.toml`. A pure function of the record and the
/// relative path from the shim to the real tree — regenerating it is always a
/// no-op when nothing moved, which is what makes the file safe to track.
///
/// The shim carries a `[build-system]` because it IS its own project root:
/// unlike p6m's in-tree overlay, the real tree's `setup.py` never runs for
/// this dist. `package-dir` and `packages.find.where` both point at the real
/// tree, so setuptools' editable finder maps the package names onto files
/// under the real tree and an edit there is live with no reinstall.
pub fn render_shim_pyproject(project: &str, entry: &PathSourceEntry, rel_to_real: &str) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_MARKER);
    out.push('\n');
    out.push_str(
        "#\n\
         # Source of truth: ../../path-sources/<project>.toml, beside the pack\n\
         # manifest. This file is a pure function of that record plus the\n\
         # relative path to the real tree, regenerated on every initialize.\n\
         #\n\
         # It exists so pixi's own resolver can read this source's metadata\n\
         # without running a PEP 517 metadata build (which costs a whole conda\n\
         # build environment per tree). The importable code is NOT here: it is\n\
         # the real tree named below, reached by a relative package-dir, so an\n\
         # editable install of this shim imports and live-edits that tree.\n",
    );
    out.push_str("\n[build-system]\n");
    out.push_str("requires = [\"setuptools>=64\"]\n");
    out.push_str("build-backend = \"setuptools.build_meta\"\n");
    out.push_str("\n[project]\n");
    out.push_str(&format!("name = {}\n", toml_string(project)));
    out.push_str(&format!("version = {}\n", toml_string(&entry.version)));
    if let Some(rp) = entry.requires_python.as_deref() {
        out.push_str(&format!("requires-python = {}\n", toml_string(rp)));
    }
    out.push_str(&format!(
        "dependencies = {}\n",
        toml_array(&entry.dependencies)
    ));
    out.push_str("\n[tool.setuptools.package-dir]\n");
    out.push_str(&format!("\"\" = {}\n", toml_string(rel_to_real)));
    out.push_str("\n[tool.setuptools.packages.find]\n");
    out.push_str(&format!("where = [{}]\n", toml_string(rel_to_real)));
    out.push_str(&format!(
        "include = {}\n",
        toml_array(&entry.include_globs(project))
    ));
    out.push_str("namespaces = true\n");
    out.push_str(GENERATED_END);
    out.push('\n');
    out
}

fn toml_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn toml_array(values: &[String]) -> String {
    if values.is_empty() {
        return "[]".to_string();
    }
    format!(
        "[{}]",
        values
            .iter()
            .map(|v| toml_string(v))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

/// `a/b/c` from the workspace root to `target`, refusing anything outside it.
fn pathdiff_from_root(canonical_root: &Path, target: &Path) -> Result<String> {
    // The shim may not exist yet, so canonicalize the deepest existing parent
    // and re-attach the tail.
    let mut tail = Vec::new();
    let mut probe = target.to_path_buf();
    let canonical = loop {
        match probe.canonicalize() {
            Ok(c) => break c,
            Err(_) => {
                let Some(name) = probe.file_name().map(|n| n.to_os_string()) else {
                    bail!("cannot locate {} under a workspace root", target.display());
                };
                tail.push(name);
                if !probe.pop() {
                    bail!("cannot locate {} under a workspace root", target.display());
                }
            }
        }
    };
    let mut full = canonical;
    for name in tail.iter().rev() {
        full.push(name);
    }
    let rel = full.strip_prefix(canonical_root).map_err(|_| {
        anyhow::anyhow!(
            "{} resolves to {}, which is outside the workspace root {}",
            target.display(),
            full.display(),
            canonical_root.display()
        )
    })?;
    Ok(rel.to_string_lossy().replace('\\', "/"))
}

/// The relative path a file inside `shim_rel` uses to reach `real_rel`, both
/// given relative to the same workspace root.
fn relative_from_shim(shim_rel: &str, real_rel: &str) -> String {
    let up = shim_rel.split('/').filter(|s| !s.is_empty()).count();
    let mut out = String::new();
    for _ in 0..up {
        out.push_str("../");
    }
    out.push_str(real_rel);
    out
}

/// EVERY write in this module goes through here. `text: None` means "I am
/// about to create this directory".
///
/// The scope check is the point: retread owns the pack directory and nothing
/// else, and the whole reason p6m-b exists is that p6m wrote into trees we do
/// not own. Pointing the writer at `third_party/…` fails here, which is the
/// RED control for this capability.
fn write_under_pack(pack_dir: &Path, target: &Path, text: Option<&str>) -> Result<()> {
    let canonical_pack = pack_dir
        .canonicalize()
        .with_context(|| format!("canonicalizing pack directory {}", pack_dir.display()))?;
    // Resolve as far as exists, then re-attach — the target may be new.
    let mut tail = Vec::new();
    let mut probe = target.to_path_buf();
    let resolved = loop {
        match probe.canonicalize() {
            Ok(c) => break c,
            Err(_) => {
                let Some(name) = probe.file_name().map(|n| n.to_os_string()) else {
                    bail!(
                        "refusing to write {}: it has no locatable parent",
                        target.display()
                    );
                };
                tail.push(name);
                if !probe.pop() {
                    bail!(
                        "refusing to write {}: it has no locatable parent",
                        target.display()
                    );
                }
            }
        }
    };
    let mut full = resolved;
    for name in tail.iter().rev() {
        full.push(name);
    }
    if !full.starts_with(&canonical_pack) {
        bail!(
            "refusing to write {} (resolves to {}): it is outside this pack's own \
             directory {}. retread writes generated shims into the pack layer and \
             NOWHERE else — never into a source tree.",
            target.display(),
            full.display(),
            canonical_pack.display()
        );
    }
    let Some(text) = text else {
        return Ok(());
    };
    atomic_replace(target, text)
}

/// Replace `file` with `text` WITHOUT ever opening `file` for writing.
///
/// A staged workspace hardlinks its trees out of a shared mirror, so a target
/// can be one of N links to an inode the job must not modify. Writing in
/// place writes through every one of those links; writing a sibling and
/// renaming replaces the directory ENTRY only.
fn atomic_replace(file: &Path, text: &str) -> Result<()> {
    let dir = file
        .parent()
        .ok_or_else(|| anyhow::anyhow!("{} has no parent directory", file.display()))?;
    let tmp = dir.join(format!(
        ".{}.retread-p6mb.{}.tmp",
        file.file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("pyproject.toml"),
        std::process::id()
    ));
    let _ = std::fs::remove_file(&tmp);
    std::fs::write(&tmp, text).with_context(|| format!("writing {}", tmp.display()))?;
    std::fs::rename(&tmp, file)
        .with_context(|| format!("renaming {} onto {}", tmp.display(), file.display()))?;
    Ok(())
}

/// Read the shim back and prove it is what uv needs. A shim that produced
/// something uv would refuse is worse than none: it is a silent return to the
/// metadata build with a generated file to explain.
fn verify_shim(file: &Path, project: &str, entry: &PathSourceEntry) -> Result<()> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::MetadataExt as _;
        let links = std::fs::metadata(file)
            .with_context(|| format!("stat {}", file.display()))?
            .nlink();
        if links != 1 {
            bail!(
                "{} has {links} hard links after the write; a shared inode may \
                 have been modified",
                file.display()
            );
        }
    }
    let text = std::fs::read_to_string(file)
        .with_context(|| format!("re-reading {}", file.display()))?;
    let parsed: toml::Value =
        toml::from_str(&text).with_context(|| format!("re-parsing {}", file.display()))?;
    let table = parsed
        .get("project")
        .ok_or_else(|| anyhow::anyhow!("{} has no [project] table", file.display()))?;
    let name = table.get("name").and_then(|v| v.as_str()).unwrap_or_default();
    if normalize_dist_name(name) != normalize_dist_name(project) {
        bail!("{} declares name {name}, wanted {project}", file.display());
    }
    let version = table.get("version").and_then(|v| v.as_str()).unwrap_or_default();
    if version != entry.version {
        bail!(
            "{} declares version {version}, wanted {}",
            file.display(),
            entry.version
        );
    }
    if table.get("dependencies").and_then(|v| v.as_array()).is_none() {
        bail!("{} has no static `dependencies` array", file.display());
    }
    if entry.requires_python.is_some() && table.get("requires-python").is_none() {
        bail!("{} lost its `requires-python`", file.display());
    }
    if let Some(dynamic) = table.get("dynamic").and_then(|v| v.as_array()) {
        for value in dynamic {
            let field = value.as_str().unwrap_or_default().to_ascii_lowercase();
            if REQUIRED_STATIC_FIELDS.contains(&field.as_str()) {
                bail!(
                    "{} lists `{field}` as dynamic, which forces the metadata \
                     build this shim exists to avoid",
                    file.display()
                );
            }
        }
    }
    // The shim must point somewhere: a shim with no package-dir installs an
    // empty distribution, which imports as a missing module at runtime.
    let package_dir = parsed
        .get("tool")
        .and_then(|t| t.get("setuptools"))
        .and_then(|s| s.get("package-dir"))
        .and_then(|p| p.get(""))
        .and_then(|v| v.as_str());
    let Some(package_dir) = package_dir else {
        bail!(
            "{} has no [tool.setuptools.package-dir] \"\" entry, so an editable \
             install of it would contain no code",
            file.display()
        );
    };
    let resolved = file
        .parent()
        .map(|d| d.join(package_dir))
        .ok_or_else(|| anyhow::anyhow!("{} has no parent", file.display()))?;
    if !resolved.is_dir() {
        bail!(
            "{} points package-dir at {}, which resolves to {} and is not a \
             directory",
            file.display(),
            package_dir,
            resolved.display()
        );
    }
    Ok(())
}

fn find_pkg_info(dir: &Path) -> Result<Option<PathBuf>> {
    let mut found: Option<PathBuf> = None;
    for entry in std::fs::read_dir(dir).with_context(|| format!("reading {}", dir.display()))? {
        let entry = entry?;
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let is_egg_info = path
            .file_name()
            .and_then(|n| n.to_str())
            .is_some_and(|n| n.ends_with(".egg-info"));
        if !is_egg_info {
            continue;
        }
        let candidate = path.join("PKG-INFO");
        if candidate.is_file() {
            // More than one egg-info is ambiguous: do not guess which one the
            // build would have produced.
            if found.is_some() {
                return Ok(None);
            }
            found = Some(candidate);
        }
    }
    Ok(found)
}

/// The declared sources, for the backend's own log line.
pub fn declared_summary(records: &[PathSourceRecord]) -> String {
    records
        .iter()
        .map(|r| format!("{}@{}", r.project, r.entry.path))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Unused today, kept so `BTreeMap` stays imported for the tests' fixtures.
pub type PathSourceMap = BTreeMap<String, PathSourceEntry>;

#[cfg(test)]
mod tests {
    use super::*;

    fn test_dir(label: &str) -> PathBuf {
        use std::sync::atomic::{AtomicU64, Ordering};
        static SEQ: AtomicU64 = AtomicU64::new(0);
        let dir = std::env::temp_dir().join(format!(
            "retread-p6mb-{label}-{}-{}",
            std::process::id(),
            SEQ.fetch_add(1, Ordering::Relaxed)
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    const PACE_REL: &str = "third_party/pace-sim2real/source/pace_sim2real";
    const PACK_REL: &str = "pypi-packs/isaaclab-2.3x-pack";
    const SHIM_REL: &str = "pypi-packs/isaaclab-2.3x-pack/sources/pace-sim2real";

    /// A workspace whose manifest points `pace_sim2real` at the SHIM (which is
    /// what p6m-b's manifest change does), a pack directory, and a real tree
    /// carrying its own `*.egg-info/PKG-INFO` — pace-sim2real's live shape.
    fn workspace(label: &str) -> PathBuf {
        let root = test_dir(label);
        std::fs::write(
            root.join("pixi.toml"),
            format!(
                "[workspace]\nname = \"ws\"\n\n[pypi-dependencies]\n\
                 pace_sim2real = {{ path = \"{SHIM_REL}\", editable = true }}\n"
            ),
        )
        .unwrap();
        std::fs::create_dir_all(root.join(PACE_REL).join("pace_sim2real")).unwrap();
        std::fs::write(
            root.join(PACE_REL).join("pace_sim2real").join("__init__.py"),
            "",
        )
        .unwrap();
        std::fs::create_dir_all(root.join(PACE_REL).join("pace_sim2real.egg-info")).unwrap();
        std::fs::write(
            root.join(PACE_REL)
                .join("pace_sim2real.egg-info")
                .join("PKG-INFO"),
            "Metadata-Version: 2.1\nName: pace_sim2real\nVersion: 0.1.2\n\
             Requires-Python: >=3.10\nRequires-Dist: psutil\nRequires-Dist: cmaes\n\n\
             body\n",
        )
        .unwrap();
        std::fs::create_dir_all(root.join(PACK_REL)).unwrap();
        std::fs::write(root.join(PACK_REL).join("pixi.toml"), "[package]\n").unwrap();
        root
    }

    fn pace_entry() -> PathSourceEntry {
        PathSourceEntry {
            path: PACE_REL.to_string(),
            version: "0.1.2".to_string(),
            requires_python: Some(">=3.10".to_string()),
            dependencies: vec!["psutil".to_string(), "cmaes".to_string()],
            packages_include: Vec::new(),
        }
    }

    /// Write the record file — the hand-editable source of truth.
    fn write_record(root: &Path, project: &str, entry: &PathSourceEntry) -> PathBuf {
        let dir = root.join(PACK_REL).join(RECORDS_DIR_DEFAULT);
        std::fs::create_dir_all(&dir).unwrap();
        let file = dir.join(format!("{project}.toml"));
        std::fs::write(&file, render_record(project, entry)).unwrap();
        file
    }

    fn config(gate: Option<bool>) -> RetreadConfig {
        let mut cfg: RetreadConfig = serde_json::from_value(serde_json::json!({
            "retread-wheels": { "placeholder": { "version": "==1.0.0" } },
        }))
        .unwrap();
        cfg.path_source_metadata = gate;
        cfg
    }

    fn pack_manifest(root: &Path) -> PathBuf {
        root.join(PACK_REL).join("pixi.toml")
    }

    /// GUARD 1 — the whole capability, end to end. A record beside the pack
    /// manifest produces a shim INSIDE the pack directory that carries every
    /// field uv needs statically and points its package-dir at the real tree.
    /// Nothing under the real tree is created or modified.
    #[test]
    fn a_pack_record_generates_a_shim_that_points_at_the_real_tree() {
        let root = workspace("happy");
        write_record(&root, "pace-sim2real", &pace_entry());
        let tree_before = tree_listing(&root.join(PACE_REL));

        let outcomes = materialize_declared_path_sources(
            &config(Some(true)),
            Some(&root),
            Some(&pack_manifest(&root)),
        )
        .unwrap();
        assert_eq!(outcomes.len(), 1);
        assert!(
            matches!(outcomes[0], PathSourceOutcome::Written { .. }),
            "wanted a write, got {:?}",
            outcomes[0]
        );

        let shim = root.join(SHIM_REL).join("pyproject.toml");
        let text = std::fs::read_to_string(&shim).unwrap();
        let parsed: toml::Value = toml::from_str(&text).unwrap();
        let project = parsed.get("project").expect("no [project] table");
        assert_eq!(project.get("name").unwrap().as_str().unwrap(), "pace-sim2real");
        assert_eq!(project.get("version").unwrap().as_str().unwrap(), "0.1.2");
        assert_eq!(
            project.get("requires-python").unwrap().as_str().unwrap(),
            ">=3.10"
        );
        let deps: Vec<&str> = project
            .get("dependencies")
            .unwrap()
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap())
            .collect();
        assert_eq!(deps, vec!["psutil", "cmaes"]);
        assert!(
            project.get("dynamic").is_none(),
            "the shim owns its own build; nothing may be dynamic"
        );

        // The package-dir must RESOLVE to the real tree, not merely be a string.
        let package_dir = parsed["tool"]["setuptools"]["package-dir"][""]
            .as_str()
            .unwrap();
        let resolved = root.join(SHIM_REL).join(package_dir).canonicalize().unwrap();
        assert_eq!(resolved, root.join(PACE_REL).canonicalize().unwrap());

        // The real tree is untouched: same entries, same bytes.
        assert_eq!(tree_before, tree_listing(&root.join(PACE_REL)));
    }

    fn tree_listing(dir: &Path) -> Vec<(PathBuf, Vec<u8>)> {
        let mut out = Vec::new();
        let mut stack = vec![dir.to_path_buf()];
        while let Some(d) = stack.pop() {
            for e in std::fs::read_dir(&d).unwrap() {
                let p = e.unwrap().path();
                if p.is_dir() {
                    stack.push(p);
                } else {
                    let bytes = std::fs::read(&p).unwrap();
                    out.push((p, bytes));
                }
            }
        }
        out.sort();
        out
    }

    /// GUARD 2 — the shim is a PURE FUNCTION of the record, so regenerating it
    /// is a no-op. That is what makes it safe to track in git: a committed shim
    /// plus an unchanged record never produces a diff.
    #[test]
    fn regenerating_the_shim_from_the_same_record_writes_nothing() {
        let root = workspace("idempotent");
        write_record(&root, "pace-sim2real", &pace_entry());
        let cfg = config(Some(true));
        let first =
            materialize_declared_path_sources(&cfg, Some(&root), Some(&pack_manifest(&root)))
                .unwrap();
        assert!(matches!(first[0], PathSourceOutcome::Written { .. }));
        let shim = root.join(SHIM_REL).join("pyproject.toml");
        let bytes = std::fs::read(&shim).unwrap();

        let second =
            materialize_declared_path_sources(&cfg, Some(&root), Some(&pack_manifest(&root)))
                .unwrap();
        assert!(
            matches!(second[0], PathSourceOutcome::Unchanged { .. }),
            "a second run must not rewrite the shim, got {:?}",
            second[0]
        );
        assert_eq!(bytes, std::fs::read(&shim).unwrap());
    }

    /// GUARD 3 — RED CONTROL for the write scope. This is the defect p6m-b
    /// exists to remove: retread must never write into a source tree. Aiming
    /// the writer at the real tree fails, and the message names the pack
    /// directory it is confined to.
    #[test]
    fn a_write_outside_the_pack_directory_is_refused() {
        let root = workspace("scope");
        let pack = root.join(PACK_REL);
        let inside = pack.join(SHIMS_DIR).join("pace-sim2real").join("pyproject.toml");
        std::fs::create_dir_all(inside.parent().unwrap()).unwrap();
        write_under_pack(&pack, &inside, Some("ok\n")).expect("a write inside the pack must work");
        assert_eq!(std::fs::read_to_string(&inside).unwrap(), "ok\n");

        let outside = root.join(PACE_REL).join("pyproject.toml");
        let error = write_under_pack(&pack, &outside, Some("[project]\n"))
            .expect_err("writing into the source tree must be refused");
        let text = format!("{error:#}");
        assert!(
            text.contains("outside this pack's own directory"),
            "message must say why: {text}"
        );
        assert!(
            !outside.exists(),
            "the refusal must happen BEFORE the file appears"
        );
    }

    /// GUARD 3b — RED CONTROL for the live harness. A directory that is not a
    /// pack is not a write root, even when it holds a records directory that
    /// would otherwise make the generator write a shim into it. This is what
    /// stops `--pack third_party/…` from turning a source tree into a pack.
    #[test]
    fn a_directory_with_no_pack_manifest_is_not_a_write_root() {
        let root = workspace("not-a-pack");
        let fake = root.join("third_party");
        std::fs::create_dir_all(fake.join(RECORDS_DIR_DEFAULT)).unwrap();
        std::fs::write(
            fake.join(RECORDS_DIR_DEFAULT).join("pace-sim2real.toml"),
            render_record("pace-sim2real", &pace_entry()),
        )
        .unwrap();
        let error = generate_shims(&fake, &root, RECORDS_DIR_DEFAULT, None)
            .expect_err("a non-pack directory must be refused");
        assert!(
            format!("{error:#}").contains("is not a pack directory"),
            "{error:#}"
        );
        assert!(!fake.join(SHIMS_DIR).exists(), "it created a shim anyway");
    }

    /// GUARD 4 — drift on `version`. The record is a claim about a tree that
    /// upstream bumps; a stale claim is a lock that names a version the
    /// installed tree does not have. The refusal names the RECORD FILE (what to
    /// edit) and the tree file that disagrees.
    #[test]
    fn a_record_whose_version_drifts_from_the_tree_is_refused_naming_both_files() {
        let root = workspace("drift-version");
        let mut entry = pace_entry();
        entry.version = "0.9.9".to_string();
        let record_file = write_record(&root, "pace-sim2real", &entry);

        let error = materialize_declared_path_sources(
            &config(Some(true)),
            Some(&root),
            Some(&pack_manifest(&root)),
        )
        .expect_err("stale version must be refused");
        let text = format!("{error:#}");
        assert!(text.contains("0.9.9"), "must quote the record's value: {text}");
        assert!(text.contains("0.1.2"), "must quote the tree's value: {text}");
        assert!(
            text.contains(&record_file.display().to_string()),
            "must name the file to edit: {text}"
        );
        assert!(
            text.contains("PKG-INFO"),
            "must name the tree file that disagrees: {text}"
        );
        assert!(
            !root.join(SHIM_REL).exists(),
            "a drifted record must not produce a shim"
        );
    }

    /// GUARD 5 — drift on `requires-python` and on `dependencies` too, not just
    /// version. A dependency the record omits is a dependency the resolver
    /// never sees, which is a wrong lock rather than a slow one.
    #[test]
    fn drift_on_requires_python_or_dependencies_is_refused_as_well() {
        for (label, mutate) in [
            (
                "rp",
                Box::new(|e: &mut PathSourceEntry| e.requires_python = Some(">=3.8".into()))
                    as Box<dyn Fn(&mut PathSourceEntry)>,
            ),
            (
                "deps",
                Box::new(|e: &mut PathSourceEntry| e.dependencies = vec!["psutil".into()]),
            ),
        ] {
            let root = workspace(&format!("drift-{label}"));
            let mut entry = pace_entry();
            mutate(&mut entry);
            write_record(&root, "pace-sim2real", &entry);
            let error = materialize_declared_path_sources(
                &config(Some(true)),
                Some(&root),
                Some(&pack_manifest(&root)),
            )
            .expect_err("drift on {label} must be refused");
            let text = format!("{error:#}");
            assert!(
                text.contains("path-source record drift"),
                "{label}: {text}"
            );
            assert!(!root.join(SHIM_REL).exists(), "{label}: shim written anyway");
        }
    }

    /// GUARD 6 — "update as needed". `refresh` rebuilds the record FROM the
    /// tree, and the rebuilt record is exactly what stops the drift refusal —
    /// so the operator's one command produces a record the next run accepts.
    #[test]
    fn refresh_rebuilds_the_record_from_the_tree_and_the_next_run_accepts_it() {
        let root = workspace("refresh");
        let mut stale = pace_entry();
        stale.version = "0.0.1".to_string();
        stale.dependencies = vec!["psutil".to_string()];
        let record_file = write_record(&root, "pace-sim2real", &stale);

        let facts = tree_facts(&root.join(PACE_REL)).unwrap();
        let refreshed = record_from_tree("pace-sim2real", &stale, &facts).unwrap();
        assert_eq!(refreshed.version, "0.1.2");
        assert_eq!(refreshed.dependencies, vec!["psutil", "cmaes"]);
        assert_eq!(
            refreshed.path, stale.path,
            "refresh must never move the path; the tree does not state it"
        );

        std::fs::write(&record_file, render_record("pace-sim2real", &refreshed)).unwrap();
        let outcomes = materialize_declared_path_sources(
            &config(Some(true)),
            Some(&root),
            Some(&pack_manifest(&root)),
        )
        .expect("the refreshed record must be accepted");
        assert!(matches!(outcomes[0], PathSourceOutcome::Written { .. }));

        // and the file round-trips: what refresh wrote is what load_records reads.
        let reloaded = load_records(&root.join(PACK_REL), RECORDS_DIR_DEFAULT).unwrap();
        assert_eq!(reloaded.len(), 1);
        assert_eq!(reloaded[0].entry, refreshed);
    }

    /// GUARD 7 — a tree with NO egg-info still states facts, in `setup.py`.
    /// This is ProtoMotions' shape, and it is the only reason its drift can be
    /// detected at all.
    #[test]
    fn setup_py_literals_are_read_when_the_tree_ships_no_egg_info() {
        let dir = test_dir("setuppy");
        std::fs::write(
            dir.join("setup.py"),
            "from setuptools import setup\nsetup(\n    name=\"protomotions\",\n\
                 version=\"3.1\",\n    python_requires=\">=3.8\",\n)\n",
        )
        .unwrap();
        let facts = tree_facts(&dir).unwrap();
        assert_eq!(facts.version.as_ref().unwrap().value, "3.1");
        assert_eq!(facts.requires_python.as_ref().unwrap().value, ">=3.8");
        assert_eq!(facts.name.as_ref().unwrap().value, "protomotions");
        assert!(
            facts.dependencies.is_none(),
            "a tree that states nothing about deps must not be read as stating []"
        );
        assert!(
            facts.version.as_ref().unwrap().source.ends_with("setup.py"),
            "the refusal has to be able to name the file"
        );
    }

    /// GUARD 8 — the reader/writer tie. retread does not invent path sources:
    /// if the workspace manifest does not point at the shim, generating one
    /// would leave a directory nothing resolves.
    #[test]
    fn a_shim_the_workspace_manifest_does_not_declare_is_refused() {
        let root = workspace("undeclared");
        // point the manifest back at the real tree, as it reads before p6m-b
        std::fs::write(
            root.join("pixi.toml"),
            format!(
                "[workspace]\nname = \"ws\"\n\n[pypi-dependencies]\n\
                 pace_sim2real = {{ path = \"{PACE_REL}\", editable = true }}\n"
            ),
        )
        .unwrap();
        write_record(&root, "pace-sim2real", &pace_entry());
        let error = materialize_declared_path_sources(
            &config(Some(true)),
            Some(&root),
            Some(&pack_manifest(&root)),
        )
        .expect_err("an undeclared shim must be refused");
        let text = format!("{error:#}");
        assert!(text.contains(SHIM_REL), "must name the path to declare: {text}");
        assert!(!root.join(SHIM_REL).exists());
    }

    /// GUARD 9 — a record whose `path` escapes the workspace root is refused
    /// before anything is read or written.
    #[test]
    fn a_path_escaping_the_workspace_root_is_refused() {
        let root = workspace("escape");
        let mut entry = pace_entry();
        entry.path = "../elsewhere".to_string();
        write_record(&root, "pace-sim2real", &entry);
        let error = materialize_declared_path_sources(
            &config(Some(true)),
            Some(&root),
            Some(&pack_manifest(&root)),
        )
        .expect_err("`..` must be refused");
        assert!(format!("{error:#}").contains("may not escape the workspace root"));
    }

    /// GUARD 10 — the gate. Off (the default) writes nothing at all, so merging
    /// this changes no existing lock; on with no record is an error rather than
    /// a silent no-op, because a gate with no producer is the defect this
    /// campaign keeps re-finding.
    #[test]
    fn the_gate_governs_both_directions() {
        let root = workspace("gate-off");
        write_record(&root, "pace-sim2real", &pace_entry());
        let outcomes =
            materialize_declared_path_sources(&config(None), Some(&root), Some(&pack_manifest(&root)))
                .unwrap();
        assert!(outcomes.is_empty());
        assert!(!root.join(SHIM_REL).exists());

        let bare = workspace("gate-on-empty");
        let error = materialize_declared_path_sources(
            &config(Some(true)),
            Some(&bare),
            Some(&pack_manifest(&bare)),
        )
        .expect_err("gate on with no records must be an error");
        assert!(format!("{error:#}").contains("A gate with no producer is a defect"));
    }

    /// GUARD 11 — the shim write never goes through a hardlink. A staged
    /// workspace is `cp -al`'d out of a shared mirror, so the target can be one
    /// of N links to an inode the job must not touch. Rename-over moves the
    /// directory entry; the twin keeps its bytes.
    #[cfg(unix)]
    #[test]
    fn the_shim_write_replaces_the_directory_entry_and_never_the_shared_inode() {
        use std::os::unix::fs::MetadataExt as _;
        let root = workspace("hardlink");
        write_record(&root, "pace-sim2real", &pace_entry());
        let shim_dir = root.join(SHIM_REL);
        std::fs::create_dir_all(&shim_dir).unwrap();
        let shim = shim_dir.join("pyproject.toml");
        std::fs::write(&shim, "STALE SHIM\n").unwrap();

        let mirror = test_dir("hardlink-mirror").join("pyproject.toml");
        std::fs::hard_link(&shim, &mirror).unwrap();
        assert_eq!(std::fs::metadata(&shim).unwrap().nlink(), 2);

        materialize_declared_path_sources(
            &config(Some(true)),
            Some(&root),
            Some(&pack_manifest(&root)),
        )
        .unwrap();

        assert_eq!(
            std::fs::read_to_string(&mirror).unwrap(),
            "STALE SHIM\n",
            "the shared inode was modified through its other link"
        );
        assert_eq!(std::fs::metadata(&shim).unwrap().nlink(), 1);
        assert!(std::fs::read_to_string(&shim).unwrap().contains("[project]"));
    }
}
