//! Static PEP 621 metadata for the workspace's local PyPI **path sources**.
//!
//! # The defect this closes
//!
//! pixi resolves `[pypi-dependencies]` entries of the form
//! `name = { path = "…", editable = true }` with its OWN uv (the frontend
//! resolver in `pixi_core::lock_file::resolve::pypi`), not with retread's
//! child uv. uv reads a path source's metadata statically only when the tree
//! carries a `[project]` table whose needed fields (`name`, `version`,
//! `requires-python`, `dependencies`) are present and are NOT listed in
//! `dynamic`. When they are not, uv logs
//!
//! ```text
//! No static `pyproject.toml` available for: pace-sim2real @ file:///… (FieldNotFound("project"))
//! Preparing metadata for: pace-sim2real @ file:///…
//! ```
//!
//! and runs a full PEP 517 `prepare_metadata_for_build_wheel`: pixi
//! instantiates a whole conda build environment for that one tree. On the
//! campaign's canonical 27-environment workspace that cost 1 714.7 s of a
//! 1 758 s lock for a 27-file, 40 KB source tree whose own build work is
//! 6.2 s.
//!
//! # Why the fix lives HERE and not upstream
//!
//! The upstream repos (`pace-sim2real`, `ProtoMotions`) are vendored source
//! we do not own, and a lock must not depend on a patch anybody has to
//! remember to apply. So retread's own **pack layer** carries the facts: a
//! pack declares its workspace's path sources under
//! `[package.build.config.retread-path-sources]`, gated by
//! `retread-path-source-metadata = true`, and retread materializes a
//! `[project]` overlay into the WORKSPACE copy of that tree at `initialize`
//! time — strictly before pixi's frontend resolves any environment's PyPI
//! set.
//!
//! # Why the overlay cannot change what the lock says
//!
//! The block is **append-only** and carries only the four fields uv needs
//! plus a `dynamic` list naming the fields the source's own build backend
//! still owns. Measured on the production toolchain (uv 0.12.5,
//! setuptools 84.0.0) for both trees: uv switches from
//! `Preparing metadata` to ``Found static `pyproject.toml` ``, and the
//! METADATA a real `prepare_metadata_for_build_wheel` produces differs from
//! the pristine tree's by exactly one line — `Dynamic: requires-dist`
//! disappears, because `requires-dist` is now static. Name, Version,
//! Summary, Requires-Python, every Requires-Dist and every Classifier are
//! byte-identical.
//!
//! # The three things this module refuses to do
//!
//! * **Write outside the workspace.** Every declared path is relative, is
//!   rejected if it carries a `..` component, and its canonical form must
//!   live under the canonical workspace root.
//! * **Write through a hardlink.** A staged workspace is `cp -al`'d out of a
//!   shared mirror, so the target file is typically a hardlinked twin of a
//!   file the job must not touch. The overlay is written to a sibling temp
//!   file and `rename`d over the name, which replaces the *directory entry*;
//!   every other link keeps the old inode. The written file is then asserted
//!   to have a link count of 1.
//! * **Touch a source that already has static metadata.** A tree with a
//!   `[project]` table is left byte-identical: uv was already reading it.

use std::collections::BTreeMap;
use std::path::{Component, Path, PathBuf};

use anyhow::{Context, Result, bail};
use serde::{Deserialize, Serialize};

use crate::config::RetreadConfig;

/// First line of the generated block. Also the idempotence key: a file that
/// already carries it was written by this code and is regenerated in place
/// rather than appended to twice.
pub const GENERATED_MARKER: &str =
    "# --- generated by pixi-build-retread (retread-path-source-metadata). Do not edit. ---";

/// Last line of the generated block.
pub const GENERATED_END: &str = "# --- end pixi-build-retread generated block ---";

/// The PEP 621 fields uv needs statically. A `dynamic` entry naming any of
/// them puts the tree straight back into a PEP 517 metadata build, so a
/// record that does it is refused rather than silently written.
pub const REQUIRED_STATIC_FIELDS: [&str; 4] =
    ["name", "version", "requires-python", "dependencies"];

/// One declared path source, from
/// `[package.build.config.retread-path-sources.<dist-name>]`.
///
/// The map key is the distribution name, exactly as `retread-wheels` is
/// keyed. Everything here is a FACT ABOUT THE SOURCE, not a preference: it
/// is what a PEP 517 metadata build of that tree produces today, and the
/// cross-check against an in-tree `*.egg-info/PKG-INFO` (when one exists)
/// refuses the write when the two disagree.
#[derive(Debug, Clone, Default, Deserialize, Serialize, PartialEq, Eq)]
#[serde(deny_unknown_fields, rename_all = "kebab-case")]
pub struct PathSourceEntry {
    /// Path to the source tree, RELATIVE to the workspace root (the
    /// directory holding the consuming `pixi.toml`) — the same string the
    /// workspace's own `[pypi-dependencies]` entry uses.
    pub path: String,

    /// The project's version, as the build backend produces it.
    pub version: String,

    /// `requires-python`, e.g. `">=3.10"`. Omitted means the source declares
    /// none.
    #[serde(default)]
    pub requires_python: Option<String>,

    /// PEP 508 runtime dependencies, in the order the source declares them.
    #[serde(default)]
    pub dependencies: Vec<String>,

    /// Fields the source's own build backend still owns — anything it sets
    /// outside `pyproject.toml` that is NOT one of
    /// [`REQUIRED_STATIC_FIELDS`]. Naming them keeps a real build's METADATA
    /// byte-identical to the pristine tree's; omitting one that `setup.py`
    /// sets silently drops it from the built wheel, and naming one that
    /// `setup.py` does NOT set makes setuptools fail with
    /// `No configuration found for dynamic '<field>'`.
    #[serde(default)]
    pub dynamic: Vec<String>,
}

/// What happened to one declared source. Every arm is reported by the
/// backend log so a run can be audited without re-reading the trees.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PathSourceOutcome {
    /// The tree already carries a `[project]` table. Left byte-identical.
    AlreadyStatic { dist: String, file: PathBuf },
    /// The overlay was written (created, or appended to a tree that had a
    /// `pyproject.toml` with no `[project]` table).
    Written { dist: String, file: PathBuf },
    /// The overlay was already present with identical bytes. No write.
    Unchanged { dist: String, file: PathBuf },
}

impl PathSourceOutcome {
    pub fn dist(&self) -> &str {
        match self {
            Self::AlreadyStatic { dist, .. }
            | Self::Written { dist, .. }
            | Self::Unchanged { dist, .. } => dist,
        }
    }

    pub fn file(&self) -> &Path {
        match self {
            Self::AlreadyStatic { file, .. }
            | Self::Written { file, .. }
            | Self::Unchanged { file, .. } => file,
        }
    }

    pub fn verb(&self) -> &'static str {
        match self {
            Self::AlreadyStatic { .. } => "already-static",
            Self::Written { .. } => "written",
            Self::Unchanged { .. } => "unchanged",
        }
    }
}

/// PEP 503 name normalization, so `pace_sim2real`, `pace-sim2real` and
/// `PACE.Sim2Real` compare equal.
pub fn normalize_dist_name(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut last_dash = false;
    for ch in name.chars() {
        if ch == '-' || ch == '_' || ch == '.' {
            if !last_dash {
                out.push('-');
                last_dash = true;
            }
        } else {
            out.push(ch.to_ascii_lowercase());
            last_dash = false;
        }
    }
    out
}

/// THE production entry point, and the one the guards call.
///
/// Both the gate and the write live behind this single name on purpose: a
/// guard that called a lower-level helper would stay green when the call in
/// `Handler::initialize` is deleted (that is exactly how p6k's first guard
/// could not fail), so the gate check is INSIDE here and the wiring test
/// drives `initialize` itself.
///
/// Returns the per-source outcomes; an empty vector means the gate is off or
/// nothing is declared. Any refusal is an `Err` — this never degrades to a
/// warning, because a silently-skipped overlay reappears as a 28-minute
/// metadata build with no line saying why.
pub fn materialize_declared_path_sources(
    config: &RetreadConfig,
    workspace_dir: Option<&Path>,
) -> Result<Vec<PathSourceOutcome>> {
    if !config.path_source_metadata.unwrap_or(false) {
        if !config.path_sources.is_empty() {
            tracing::warn!(
                "[package.build.config] declares {} retread-path-sources but \
                 retread-path-source-metadata is not true: no static metadata \
                 will be materialized and the frontend resolver will run a PEP \
                 517 metadata build for each of them.",
                config.path_sources.len()
            );
        }
        return Ok(Vec::new());
    }
    if config.path_sources.is_empty() {
        bail!(
            "retread-path-source-metadata = true but \
             [package.build.config.retread-path-sources] declares nothing. A \
             gate with no producer is a defect: either declare the workspace's \
             path sources or drop the key."
        );
    }
    let Some(workspace_root) = workspace_dir.filter(|dir| dir.join("pixi.toml").is_file()) else {
        bail!(
            "retread-path-source-metadata = true but this backend was not given \
             a workspace directory containing a pixi.toml, so the declared path \
             sources cannot be located. Paths are resolved against the \
             workspace root, never against the pack's own source directory."
        );
    };
    let manifest_text = std::fs::read_to_string(workspace_root.join("pixi.toml"))
        .with_context(|| format!("reading {}", workspace_root.join("pixi.toml").display()))?;

    let mut outcomes = Vec::with_capacity(config.path_sources.len());
    for (dist, entry) in &config.path_sources {
        let outcome = materialize_one(workspace_root, &manifest_text, dist, entry)
            .with_context(|| format!("retread-path-sources.{dist}"))?;
        tracing::info!(
            "retread-path-source-metadata: {} {} ({})",
            outcome.verb(),
            outcome.file().display(),
            outcome.dist(),
        );
        outcomes.push(outcome);
    }
    Ok(outcomes)
}

fn materialize_one(
    workspace_root: &Path,
    manifest_text: &str,
    dist: &str,
    entry: &PathSourceEntry,
) -> Result<PathSourceOutcome> {
    // ---- the record itself -------------------------------------------------
    if entry.path.trim().is_empty() {
        bail!("`path` is empty");
    }
    if entry.version.trim().is_empty() {
        bail!("`version` is empty: uv needs a static version or it builds anyway");
    }
    for field in &entry.dynamic {
        let normalized = field.trim().to_ascii_lowercase();
        if REQUIRED_STATIC_FIELDS.contains(&normalized.as_str()) {
            bail!(
                "`dynamic` names `{normalized}`, which is one of the fields uv \
                 needs statically ({}); the overlay would be written and the \
                 metadata build would happen anyway",
                REQUIRED_STATIC_FIELDS.join(", ")
            );
        }
    }

    // ---- where it may write ------------------------------------------------
    let rel = Path::new(&entry.path);
    if rel.is_absolute() {
        bail!("`path` must be relative to the workspace root, got {}", entry.path);
    }
    if rel
        .components()
        .any(|c| matches!(c, Component::ParentDir | Component::Prefix(_) | Component::RootDir))
    {
        bail!("`path` may not escape the workspace root, got {}", entry.path);
    }
    let dir = workspace_root.join(rel);
    if !dir.is_dir() {
        bail!("{} is not a directory", dir.display());
    }
    let canonical_root = workspace_root
        .canonicalize()
        .with_context(|| format!("canonicalizing {}", workspace_root.display()))?;
    let canonical_dir = dir
        .canonicalize()
        .with_context(|| format!("canonicalizing {}", dir.display()))?;
    if !canonical_dir.starts_with(&canonical_root) {
        bail!(
            "{} resolves to {}, which is outside the workspace root {}",
            entry.path,
            canonical_dir.display(),
            canonical_root.display()
        );
    }

    // ---- the reader/writer tie: the WORKSPACE must declare this source -----
    // retread does not invent path sources. If the consuming pixi.toml has no
    // `path = "<this>"` entry, the pack record is stale and the write would
    // edit a tree nobody asked about.
    if !manifest_text.contains(&format!("\"{}\"", entry.path))
        && !manifest_text.contains(&format!("'{}'", entry.path))
    {
        bail!(
            "the workspace manifest declares no path source `{}`; refusing to \
             write metadata into a tree the workspace does not resolve",
            entry.path
        );
    }

    // ---- already static? ---------------------------------------------------
    let file = dir.join("pyproject.toml");
    let existing = match std::fs::read_to_string(&file) {
        Ok(text) => Some(text),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => None,
        Err(err) => return Err(err).with_context(|| format!("reading {}", file.display())),
    };
    if let Some(text) = existing.as_deref()
        && !text.contains(GENERATED_MARKER)
    {
        let parsed: toml::Value = toml::from_str(text)
            .with_context(|| format!("parsing {} as TOML", file.display()))?;
        if parsed.get("project").is_some() {
            return Ok(PathSourceOutcome::AlreadyStatic {
                dist: dist.to_string(),
                file,
            });
        }
    }

    // ---- the facts must match what the tree's own build produced -----------
    cross_check_pkg_info(&dir, dist, entry)?;

    // ---- compose -----------------------------------------------------------
    let base = match existing.as_deref() {
        Some(text) => match text.find(GENERATED_MARKER) {
            // Regenerate in place: keep everything before our marker verbatim.
            Some(at) => text[..at].to_string(),
            None if text.is_empty() => String::new(),
            None if text.ends_with('\n') => text.to_string(),
            None => format!("{text}\n"),
        },
        None => String::new(),
    };
    let mut composed = base;
    if !composed.is_empty() && !composed.ends_with("\n\n") {
        composed.push('\n');
    }
    composed.push_str(&render_project_block(dist, entry));

    if existing.as_deref() == Some(composed.as_str()) {
        return Ok(PathSourceOutcome::Unchanged {
            dist: dist.to_string(),
            file,
        });
    }

    atomic_replace(&file, &composed)?;
    verify_written_overlay(&file, dist, entry)?;
    Ok(PathSourceOutcome::Written {
        dist: dist.to_string(),
        file,
    })
}

/// The generated `[project]` block. Deliberately no `[build-system]`: adding
/// one would change HOW the tree builds (legacy `setup.py` invocation vs a
/// PEP 517 backend), and the whole claim of this capability is that only the
/// resolver's view changes. Verified on setuptools 84.0.0 for both live
/// trees: with a `[project]`-only overlay the built METADATA is byte-identical
/// to the pristine tree's but for the now-static `Dynamic: requires-dist` line.
pub fn render_project_block(dist: &str, entry: &PathSourceEntry) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_MARKER);
    out.push('\n');
    out.push_str(
        "# The fields below are FACTS about this tree, declared in the retread\n\
         # pack that consumes it, not preferences. They exist so the frontend\n\
         # resolver can read this source's metadata without running a PEP 517\n\
         # metadata build (which costs a whole build environment per tree).\n\
         # `dynamic` names the fields this project's own build backend still\n\
         # owns, so a real build still produces the same METADATA.\n",
    );
    out.push_str("[project]\n");
    out.push_str(&format!("name = {}\n", toml_string(dist)));
    out.push_str(&format!("version = {}\n", toml_string(&entry.version)));
    if let Some(rp) = entry.requires_python.as_deref() {
        out.push_str(&format!("requires-python = {}\n", toml_string(rp)));
    }
    out.push_str("dependencies = [");
    if entry.dependencies.is_empty() {
        out.push_str("]\n");
    } else {
        out.push('\n');
        for dep in &entry.dependencies {
            out.push_str(&format!("    {},\n", toml_string(dep)));
        }
        out.push_str("]\n");
    }
    if !entry.dynamic.is_empty() {
        out.push_str("dynamic = [");
        out.push('\n');
        for field in &entry.dynamic {
            out.push_str(&format!("    {},\n", toml_string(field)));
        }
        out.push_str("]\n");
    }
    out.push_str(GENERATED_END);
    out.push('\n');
    out
}

fn toml_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Cross-check the declared facts against an in-tree `*.egg-info/PKG-INFO`
/// when the source ships one. That file is written by the source's OWN build
/// backend, so a disagreement means the pack record is stale — and a stale
/// record here would be a lock that says one thing and an installed wheel
/// that says another. Refuse, loudly, rather than write it.
fn cross_check_pkg_info(dir: &Path, dist: &str, entry: &PathSourceEntry) -> Result<()> {
    let Some(pkg_info) = find_pkg_info(dir)? else {
        return Ok(());
    };
    let text = std::fs::read_to_string(&pkg_info)
        .with_context(|| format!("reading {}", pkg_info.display()))?;
    let mut name = None;
    let mut version = None;
    let mut requires_python = None;
    let mut requires_dist = Vec::new();
    for line in text.lines() {
        if line.is_empty() {
            break; // headers end at the first blank line; the body follows
        }
        let Some((key, value)) = line.split_once(':') else {
            continue;
        };
        let value = value.trim();
        match key.to_ascii_lowercase().as_str() {
            "name" => name = Some(value.to_string()),
            "version" => version = Some(value.to_string()),
            "requires-python" => requires_python = Some(value.to_string()),
            "requires-dist" => requires_dist.push(value.to_string()),
            _ => {}
        }
    }
    if let Some(name) = name.as_deref()
        && normalize_dist_name(name) != normalize_dist_name(dist)
    {
        bail!(
            "{} says Name: {name}, the pack record says {dist}",
            pkg_info.display()
        );
    }
    if let Some(version) = version.as_deref()
        && version != entry.version
    {
        bail!(
            "{} says Version: {version}, the pack record says {}",
            pkg_info.display(),
            entry.version
        );
    }
    if let Some(rp) = requires_python.as_deref()
        && Some(rp) != entry.requires_python.as_deref()
    {
        bail!(
            "{} says Requires-Python: {rp}, the pack record says {:?}",
            pkg_info.display(),
            entry.requires_python
        );
    }
    if requires_dist != entry.dependencies {
        bail!(
            "{} lists Requires-Dist {:?}, the pack record says {:?}",
            pkg_info.display(),
            requires_dist,
            entry.dependencies
        );
    }
    Ok(())
}

fn find_pkg_info(dir: &Path) -> Result<Option<PathBuf>> {
    let mut found: Option<PathBuf> = None;
    for entry in std::fs::read_dir(dir).with_context(|| format!("reading {}", dir.display()))? {
        let entry = entry?;
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let is_egg_info = path
            .file_name()
            .and_then(|n| n.to_str())
            .is_some_and(|n| n.ends_with(".egg-info"));
        if !is_egg_info {
            continue;
        }
        let candidate = path.join("PKG-INFO");
        if candidate.is_file() {
            // More than one egg-info is ambiguous: do not guess which one the
            // build would have produced.
            if found.is_some() {
                return Ok(None);
            }
            found = Some(candidate);
        }
    }
    Ok(found)
}

/// Replace `file` with `text` WITHOUT ever opening `file` for writing.
///
/// A staged workspace hardlinks its source trees out of a shared mirror, so
/// the target is usually one of N links to an inode the job must not modify.
/// Writing in place (which is what `patch`, `>>`, and `File::create` all do)
/// writes through every one of those links. Writing a sibling and renaming
/// replaces the directory ENTRY only.
fn atomic_replace(file: &Path, text: &str) -> Result<()> {
    let dir = file
        .parent()
        .ok_or_else(|| anyhow::anyhow!("{} has no parent directory", file.display()))?;
    let tmp = dir.join(format!(
        ".{}.retread-p6m.{}.tmp",
        file.file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("pyproject.toml"),
        std::process::id()
    ));
    // A leftover temp from a killed process must never be appended to.
    let _ = std::fs::remove_file(&tmp);
    std::fs::write(&tmp, text).with_context(|| format!("writing {}", tmp.display()))?;
    std::fs::rename(&tmp, file)
        .with_context(|| format!("renaming {} onto {}", tmp.display(), file.display()))?;
    Ok(())
}

/// Read the file back and prove it is what uv needs. A write that produced
/// something uv would refuse is worse than no write at all: it is a silent
/// return to the metadata build with an edited tree to explain.
fn verify_written_overlay(file: &Path, dist: &str, entry: &PathSourceEntry) -> Result<()> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::MetadataExt as _;
        let links = std::fs::metadata(file)
            .with_context(|| format!("stat {}", file.display()))?
            .nlink();
        if links != 1 {
            bail!(
                "{} has {links} hard links after the write; a shared inode may \
                 have been modified",
                file.display()
            );
        }
    }
    let text = std::fs::read_to_string(file)
        .with_context(|| format!("re-reading {}", file.display()))?;
    let parsed: toml::Value =
        toml::from_str(&text).with_context(|| format!("re-parsing {}", file.display()))?;
    let project = parsed
        .get("project")
        .ok_or_else(|| anyhow::anyhow!("{} has no [project] table after the write", file.display()))?;
    let name = project.get("name").and_then(|v| v.as_str()).unwrap_or_default();
    if normalize_dist_name(name) != normalize_dist_name(dist) {
        bail!("{} declares name {name}, wanted {dist}", file.display());
    }
    let version = project.get("version").and_then(|v| v.as_str()).unwrap_or_default();
    if version != entry.version {
        bail!(
            "{} declares version {version}, wanted {}",
            file.display(),
            entry.version
        );
    }
    if project.get("dependencies").and_then(|v| v.as_array()).is_none() {
        bail!("{} has no static `dependencies` array", file.display());
    }
    if entry.requires_python.is_some() && project.get("requires-python").is_none() {
        bail!("{} lost its `requires-python`", file.display());
    }
    if let Some(dynamic) = project.get("dynamic").and_then(|v| v.as_array()) {
        for value in dynamic {
            let field = value.as_str().unwrap_or_default().to_ascii_lowercase();
            if REQUIRED_STATIC_FIELDS.contains(&field.as_str()) {
                bail!(
                    "{} lists `{field}` as dynamic, which forces the metadata \
                     build this overlay exists to avoid",
                    file.display()
                );
            }
        }
    }
    Ok(())
}

/// The declared sources, for the backend's own log line.
pub fn declared_summary(sources: &BTreeMap<String, PathSourceEntry>) -> String {
    sources
        .iter()
        .map(|(dist, entry)| format!("{dist}@{}", entry.path))
        .collect::<Vec<_>>()
        .join(", ")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_dir(label: &str) -> PathBuf {
        use std::sync::atomic::{AtomicU64, Ordering};
        static SEQ: AtomicU64 = AtomicU64::new(0);
        let dir = std::env::temp_dir().join(format!(
            "retread-p6m-{label}-{}-{}",
            std::process::id(),
            SEQ.fetch_add(1, Ordering::Relaxed)
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    /// A workspace whose pixi.toml declares one path source at `rel`.
    fn workspace(label: &str, rel: &str) -> PathBuf {
        let root = test_dir(label);
        std::fs::write(
            root.join("pixi.toml"),
            format!(
                "[workspace]\nname = \"ws\"\n\n[pypi-dependencies]\nthing = {{ path = \"{rel}\", editable = true }}\n"
            ),
        )
        .unwrap();
        std::fs::create_dir_all(root.join(rel)).unwrap();
        root
    }

    fn config(gate: Option<bool>, sources: Vec<(&str, PathSourceEntry)>) -> RetreadConfig {
        let mut cfg: RetreadConfig = serde_json::from_value(serde_json::json!({
            "retread-wheels": { "placeholder": { "version": "==1.0.0" } },
        }))
        .unwrap();
        cfg.path_source_metadata = gate;
        cfg.path_sources = sources
            .into_iter()
            .map(|(k, v)| (k.to_string(), v))
            .collect();
        cfg
    }

    fn pace_entry(rel: &str) -> PathSourceEntry {
        PathSourceEntry {
            path: rel.to_string(),
            version: "0.1.2".to_string(),
            requires_python: Some(">=3.10".to_string()),
            dependencies: vec!["psutil".to_string(), "cmaes".to_string()],
            dynamic: vec!["description".to_string(), "classifiers".to_string()],
        }
    }

    /// GUARD 1 -- the defect this branch exists for. A tree whose
    /// pyproject.toml has only a `[build-system]` table (pace-sim2real's
    /// shape) comes out with every field uv needs, the ORIGINAL bytes still
    /// intact as a prefix, and nothing in `dynamic` that would send uv back
    /// to a build.
    #[test]
    fn a_source_without_a_project_table_gains_one_and_keeps_its_original_bytes() {
        let rel = "third_party/pace/source/pace_sim2real";
        let root = workspace("no-project", rel);
        let original = "[build-system]\nrequires = [\"setuptools\", \"wheel\", \"toml\"]\nbuild-backend = \"setuptools.build_meta\"\n";
        std::fs::write(root.join(rel).join("pyproject.toml"), original).unwrap();

        let cfg = config(Some(true), vec![("pace_sim2real", pace_entry(rel))]);
        let outcomes = materialize_declared_path_sources(&cfg, Some(&root)).unwrap();
        assert_eq!(outcomes.len(), 1);
        assert!(
            matches!(outcomes[0], PathSourceOutcome::Written { .. }),
            "wanted a write, got {:?}",
            outcomes[0]
        );

        let text = std::fs::read_to_string(root.join(rel).join("pyproject.toml")).unwrap();
        assert!(
            text.starts_with(original),
            "the overlay must be append-only; got:\n{text}"
        );
        let parsed: toml::Value = toml::from_str(&text).unwrap();
        let project = parsed.get("project").expect("no [project] table");
        assert_eq!(project.get("name").unwrap().as_str().unwrap(), "pace_sim2real");
        assert_eq!(project.get("version").unwrap().as_str().unwrap(), "0.1.2");
        assert_eq!(
            project.get("requires-python").unwrap().as_str().unwrap(),
            ">=3.10"
        );
        let deps: Vec<&str> = project
            .get("dependencies")
            .unwrap()
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap())
            .collect();
        assert_eq!(deps, vec!["psutil", "cmaes"]);
        let dynamic: Vec<&str> = project
            .get("dynamic")
            .unwrap()
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap())
            .collect();
        for needed in REQUIRED_STATIC_FIELDS {
            assert!(
                !dynamic.contains(&needed),
                "`{needed}` must not be dynamic or uv builds anyway"
            );
        }
        // The build-system table the source shipped is untouched.
        assert_eq!(
            parsed
                .get("build-system")
                .unwrap()
                .get("build-backend")
                .unwrap()
                .as_str()
                .unwrap(),
            "setuptools.build_meta"
        );
        // And a second pass is a no-op, not a second block.
        let again = materialize_declared_path_sources(&cfg, Some(&root)).unwrap();
        assert!(
            matches!(again[0], PathSourceOutcome::Unchanged { .. }),
            "second pass must be idempotent, got {:?}",
            again[0]
        );
        assert_eq!(
            text.matches(GENERATED_MARKER).count(),
            1,
            "exactly one generated block"
        );
    }

    /// GUARD 2 -- a tree that ALREADY has static metadata is left
    /// byte-identical, because uv was already reading it and any write here
    /// would be a change to a source nobody needed to change.
    #[test]
    fn a_source_with_static_metadata_is_left_byte_identical() {
        let rel = "third_party/unitree_sdk2_python";
        let root = workspace("already-static", rel);
        let original = "[project]\nname = \"unitree-sdk2py\"\nversion = \"1.0.1\"\ndependencies = []\n";
        let file = root.join(rel).join("pyproject.toml");
        std::fs::write(&file, original).unwrap();

        let cfg = config(
            Some(true),
            vec![(
                "unitree_sdk2py",
                PathSourceEntry {
                    path: rel.to_string(),
                    // Deliberately DISAGREEING facts: they must not be
                    // written, and the disagreement must not be an error
                    // either -- the tree's own table wins outright.
                    version: "9.9.9".to_string(),
                    requires_python: None,
                    dependencies: vec![],
                    dynamic: vec![],
                },
            )],
        );
        let outcomes = materialize_declared_path_sources(&cfg, Some(&root)).unwrap();
        assert!(
            matches!(outcomes[0], PathSourceOutcome::AlreadyStatic { .. }),
            "got {:?}",
            outcomes[0]
        );
        assert_eq!(std::fs::read_to_string(&file).unwrap(), original);
    }

    /// GUARD 3 -- the staged-workspace hazard. The target is a hardlinked
    /// twin of a file outside the workspace (what `cp -al` staging produces);
    /// the twin must come out byte-identical and the written file must be
    /// the only link to its inode.
    #[test]
    fn the_overlay_replaces_the_name_and_never_writes_through_a_hardlink() {
        let rel = "third_party/pm";
        let root = workspace("hardlink", rel);
        let mirror = test_dir("hardlink-mirror");
        let twin = mirror.join("pyproject.toml");
        let original = "[build-system]\nrequires = [\"setuptools\"]\n";
        std::fs::write(&twin, original).unwrap();
        let target = root.join(rel).join("pyproject.toml");
        std::fs::hard_link(&twin, &target).unwrap();

        let cfg = config(
            Some(true),
            vec![(
                "protomotions",
                PathSourceEntry {
                    path: rel.to_string(),
                    version: "3.1".to_string(),
                    requires_python: Some(">=3.8".to_string()),
                    dependencies: vec![],
                    dynamic: vec!["description".to_string()],
                },
            )],
        );
        materialize_declared_path_sources(&cfg, Some(&root)).unwrap();

        assert_eq!(
            std::fs::read_to_string(&twin).unwrap(),
            original,
            "THE WRITE REACHED THE SHARED MIRROR"
        );
        #[cfg(unix)]
        {
            use std::os::unix::fs::MetadataExt as _;
            assert_eq!(std::fs::metadata(&target).unwrap().nlink(), 1);
            assert_eq!(std::fs::metadata(&twin).unwrap().nlink(), 1);
        }
        assert!(std::fs::read_to_string(&target).unwrap().contains("[project]"));
        // No temp file survives next to the target.
        let leftovers: Vec<_> = std::fs::read_dir(root.join(rel))
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .filter(|n| n.contains("retread-p6m"))
            .collect();
        assert!(leftovers.is_empty(), "leftover temp files: {leftovers:?}");
    }

    /// GUARD 4 -- the four refusals, each of which would otherwise put a
    /// generated file somewhere it must never appear, or put facts in it that
    /// the tree's own build contradicts.
    #[test]
    fn the_overlay_refuses_to_escape_the_workspace_or_to_contradict_the_tree() {
        // (a) a path that escapes the workspace
        let rel = "third_party/pm";
        let root = workspace("escape", rel);
        let outside = test_dir("escape-outside");
        std::fs::create_dir_all(outside.join("victim")).unwrap();
        let escaping = format!("../{}/victim", outside.file_name().unwrap().to_string_lossy());
        let mut cfg = config(
            Some(true),
            vec![(
                "victim",
                PathSourceEntry {
                    path: escaping.clone(),
                    version: "1.0".to_string(),
                    requires_python: None,
                    dependencies: vec![],
                    dynamic: vec![],
                },
            )],
        );
        let err = materialize_declared_path_sources(&cfg, Some(&root)).unwrap_err();
        assert!(
            format!("{err:#}").contains("escape the workspace root"),
            "unexpected error: {err:#}"
        );
        assert!(!outside.join("victim/pyproject.toml").exists());

        // (b) a source the workspace manifest does not declare
        std::fs::create_dir_all(root.join("third_party/stranger")).unwrap();
        cfg.path_sources = [(
            "stranger".to_string(),
            PathSourceEntry {
                path: "third_party/stranger".to_string(),
                version: "1.0".to_string(),
                requires_python: None,
                dependencies: vec![],
                dynamic: vec![],
            },
        )]
        .into_iter()
        .collect();
        let err = materialize_declared_path_sources(&cfg, Some(&root)).unwrap_err();
        assert!(
            format!("{err:#}").contains("declares no path source"),
            "unexpected error: {err:#}"
        );
        assert!(!root.join("third_party/stranger/pyproject.toml").exists());

        // (c) a record that contradicts the tree's own PKG-INFO
        let egg = root.join(rel).join("thing.egg-info");
        std::fs::create_dir_all(&egg).unwrap();
        std::fs::write(
            egg.join("PKG-INFO"),
            "Metadata-Version: 2.4\nName: protomotions\nVersion: 3.1\nRequires-Python: >=3.8\n",
        )
        .unwrap();
        cfg.path_sources = [(
            "protomotions".to_string(),
            PathSourceEntry {
                path: rel.to_string(),
                version: "4.0".to_string(), // the tree says 3.1
                requires_python: Some(">=3.8".to_string()),
                dependencies: vec![],
                dynamic: vec![],
            },
        )]
        .into_iter()
        .collect();
        let err = materialize_declared_path_sources(&cfg, Some(&root)).unwrap_err();
        assert!(
            format!("{err:#}").contains("Version: 3.1"),
            "unexpected error: {err:#}"
        );
        assert!(!root.join(rel).join("pyproject.toml").exists());

        // (d) a record that makes a needed field dynamic
        cfg.path_sources = [(
            "protomotions".to_string(),
            PathSourceEntry {
                path: rel.to_string(),
                version: "3.1".to_string(),
                requires_python: Some(">=3.8".to_string()),
                dependencies: vec![],
                dynamic: vec!["version".to_string()],
            },
        )]
        .into_iter()
        .collect();
        let err = materialize_declared_path_sources(&cfg, Some(&root)).unwrap_err();
        assert!(
            format!("{err:#}").contains("needs statically"),
            "unexpected error: {err:#}"
        );
        assert!(!root.join(rel).join("pyproject.toml").exists());
    }

    /// GUARD 5 -- the gate. With the key absent or false NOTHING is written,
    /// and a gate turned on with nothing declared is refused rather than
    /// silently doing nothing (a gate with no producer is a defect).
    #[test]
    fn the_gate_is_off_by_default_and_refuses_to_be_on_with_nothing_declared() {
        let rel = "third_party/pace";
        let root = workspace("gate", rel);
        let entry = pace_entry(rel);

        for gate in [None, Some(false)] {
            let cfg = config(gate, vec![("pace_sim2real", entry.clone())]);
            let outcomes = materialize_declared_path_sources(&cfg, Some(&root)).unwrap();
            assert!(outcomes.is_empty(), "gate {gate:?} materialized {outcomes:?}");
            assert!(
                !root.join(rel).join("pyproject.toml").exists(),
                "gate {gate:?} wrote a file"
            );
        }

        let empty = config(Some(true), vec![]);
        let err = materialize_declared_path_sources(&empty, Some(&root)).unwrap_err();
        assert!(
            format!("{err:#}").contains("declares nothing"),
            "unexpected error: {err:#}"
        );

        // And with no workspace root there is nowhere to write: refuse.
        let cfg = config(Some(true), vec![("pace_sim2real", entry)]);
        let err = materialize_declared_path_sources(&cfg, None).unwrap_err();
        assert!(
            format!("{err:#}").contains("workspace directory"),
            "unexpected error: {err:#}"
        );
    }
}
